### ISSUE TITLE
tel: links

### ISSUE THREAD

**Issue by yellobes** [mozilla/bleach#102]
Bleach wipes tel: links away.

An `r'\D'` filter would work for me, but I imagine that wouldn't really be quite right for some people.

On the other hand, since leaving your telephone number on a site is a little, um.. `r'\D'` might be a workable, simple fix, unless this is a feature.

**Comment by ianjosephwilson** [comment]
This seems to only happen in clean and not linkify.

If I mutate the allowed protocols on the global base class then tel links seem to make it through.  Maybe this would be an easy way to expose this to people that wanted it for whatever reason.

```
from bleach.sanitizer import BleachSanitizer
BleachSanitizer.allowed_protocols += ['tel']
```

**Comment by willkg** [comment]
Switching this over to clean label since it's not a linkify issue. If that's not correct, please let me know.

**Comment by willkg** [comment]
Bleach 1.5 allows you to specify allowed protocols which I think solves this problem. If not, let me know and I'll re-open.
