### ISSUE TITLE
Docs Deficiency - Javascript Stripping

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#108]
Bleach doesn't mention if it strips javascript from links (it does!).

I ended up writing this test , which passes, for test_basic

```
def test_javascript_link():
    ATTR = {
        'a': ['href',],
    }
    TAG = ['a']
    dirty = (u"""Start <a href="javascript:alert('BUY VIAGRA')";>Buy Viagra!</a> End""")
    clean = u'Start <a>Buy Viagra!</a> End'
    eq_(clean, bleach.clean(dirty, tags=TAG, attributes=ATTR, strip=True))
```

and it ends up mirroring , pretty exactly, existing tests in tests_security
- test_invalid_attr_value
- test_invalid_href_attr

I should have looked in that test module first. It was silly of me not to.  the docs don't mention all the smart security/javascript stripping this library does.  (thanks!)

**Comment by willkg** [comment]
I'm not sure this is worth adding to the docs, but it'd make a great "using bleach to do xyz" kind of blog post.

Given that this has been around for 4 years and nothing has happened, I'm going to take that to mean that others agree. I'm going to close this out.
