### ISSUE TITLE
create re-usable Cleaner class

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#125]
While glancing at the source, the inner workings of `clean()` caught my eye.

The current structure creates 2 object instances to clean a single bit of text.  If you do a lot of cleaning to a standard configuration, a factory pattern works really well.

I tried something and set up a test suite to see if there would be a noticeable difference.  html5lib tends to be bulky and annoying, and it often lends well to caching.  

Using the factory pattern below to cache a "cleaner", we average a 15% speedup over the default `clean` if you clean more than 10 items.  if you're doing hundreds of items, the savings seems to be over 40%.

```
class _AbstractBleachCleaner(object):
    """abstract object to cache the `sanitizer` and `parser` objects, and expose a `clean` method"""
    sanitizer = None
    parser = None

    def clean(self, text):
        """cleans text using the cached parser"""
        if not text:
            return ''
        text = force_unicode(text)    
        return _render(self.parser.parseFragment(text))

def cleaner_factory( tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES,
          styles=ALLOWED_STYLES, strip=False, strip_comments=True):
    """Generates a custom bleach Cleaner that can be re-used."""
    class s(BleachSanitizer):
        allowed_elements = tags
        allowed_attributes = attributes
        allowed_css_properties = styles
        strip_disallowed_elements = strip
        strip_html_comments = strip_comments
    p = html5lib.HTMLParser(tokenizer=s)
    customCleaner = _AbstractBleachCleaner()
    customCleaner.sanitizer = s
    customCleaner.parser = p
    return customCleaner

myCleaner = cleaner_factory()
print myCleaner.clean( sample_text ) 
```

**Comment by willkg** [comment]
I finally looked into this and did some tinkering with Bleach 2.0 rewrite.

I like the idea of having a `Cleaner` class that captures settings and reuses html5lib bits that can be reused. I'm going to implement that for Bleach 2.0.

**Comment by willkg** [comment]
This is done in PR #257. It'll be in Bleach 2.0.
