### ISSUE TITLE
Bleach linkify vs oembed content.

### ISSUE THREAD

**Issue by pypetey** [mozilla/bleach#127]
Hey,

I tried to use bleach.linkify with oembed text parsing tool and the problem is that it will make some mess and make it impossible to embed content :)

```
def get_description(self):
    providers = micawber.bootstrap_basic()
    description = bleach.clean(self.description)
    description = micawber.parse_text(description, providers)
    description = bleach.linkify(description)
```

Any ideas how to get around this problem?

**Comment by affan2** [comment]
Hi. Did this ever get resolved? Running into the same issue using bleach.linkify()

This is the original HTML
```
<div data-oembed-url="https://www.youtube.com/watch?v=ZZBFGz-wgrw">
<div>
<div style="left: 0px; width: 100%; height: 0px; position: relative; padding-bottom: 56.2493%;"><iframe allowfullscreen="" data-iframely-url="https://www.youtube.com/embed/ZZBFGz-wgrw?wmode=transparent&amp;rel=0&amp;autohide=1&amp;showinfo=0&amp;enablejsapi=1" frameborder="0" style="top: 0px; left: 0px; width: 100%; height: 100%; position: absolute;"></iframe></div>
</div>
<script async="" charset="utf-8" src="//cdn.iframe.ly/embed.js"></script></div>
```

which gets converted to 
```
<div>
<div>

&lt;script async="" charset="utf-8" src="//&amp;lt;a href=" http:="" &lt;a="" href="http://cdn.iframe.ly" target="_blank" rel="nofollow"&gt;cdn.iframe.ly="" embed.js"="" target="_blank" rel="nofollow"&gt;<a href="http://cdn.iframe.ly/embed.js" rel="nofollow" target="_blank">cdn.iframe.ly/embed.js</a>"&gt;&lt;/script&gt;<div style="width: 100%; height: 0px;">&lt;iframe allowfullscreen="" data-iframely-url="&amp;lt;a href=" https:="" &lt;a="" href="http://www.youtube.com" target="_blank" rel="nofollow"&gt;www.youtube.com="" embed="" ZZBFGz-wgrw?wmode="transparent&amp;rel=0&amp;autohide=1&amp;showinfo=0&amp;enablejsapi=1"" target="_blank" rel="nofollow"&gt;<a href="https://www.youtube.com/embed/ZZBFGz-wgrw?wmode=transparent&amp;rel=0&amp;autohide=1&amp;showinfo=0&amp;enablejsapi=1" rel="nofollow" target="_blank">https://www.youtube.com/embed/ZZBFGz-wgrw?wmode=transparent&amp;rel=0&amp;autohide=1&amp;showinfo=0&amp;enablejsapi=1</a>" frameborder="0" style="top: 0px; left: 0px; width: 100%; height: 100%; position: absolute;"&gt;&lt;/iframe&gt;</div>
</div></div>
```

Would expect URLs inside attributes to not get linkified. Any thoughts on a workaround?

Thanks!

**Comment by willkg** [comment]
I don't think I understand this issue very well.

Can someone provide an input and the output they expected from linkify so that I can build a test case and look into it? Please use Markdown formatting so it's possible for me to parse your comment correctly.

**Comment by willkg** [comment]
No one has said anything in a little under a year, so I'm going to close this out.

Going through the comments, it seems like the real problem here is that running `clean()` and then `linkify()` produces bad output somehow. With Bleach 2.0, you don't need to do those as separate passes, you can do them at the same time.

More details here:

https://bleach.readthedocs.io/en/latest/linkify.html#using-bleach-linkifier-linkifyfilter

Hope that helps!
