### ISSUE TITLE
Demo site for Bleach

### ISSUE THREAD

**Issue by soaj1664** [mozilla/bleach#134]
Hi Guys!

Is there any demo site where one can test Bleach's XSS protection? e.g., I mean something like that: http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawedSafeModeTest.php

If Bleach offers different contexts then it would be great that the demo site will support different contexts ... 
e.g.,
`<div style="Output reflects here after passing through Bleach"></div>`

**Comment by willkg** [comment]
There is no demo site that I'm aware of. I don't want to set one up and maintain it.

If someone wants to set one up and maintain it, I think that should be a separate project. Given that, I'm going to close this out.
