### ISSUE TITLE
bug/request- support for boolean attributes

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#157]
html attributes can either be name/value pairs OR boolean attributes.  

most boolean attributes can be handled by using the key as the value.

e.g. these two are the same

```
<input type="checkbox" name="foo" value="bar" checked />
<input type="checkbox" name="foo" value="bar" checked="checked" />
```

some boolean attributes aren't very well documented on how they're interpreted.  for example, how schema.org uses itemscope (https://schema.org/docs/gs.html#microdata_itemscope_itemtype)

```
<div itemscope itemtype="http://schema.org/Movie"></div>
```

running this through bleach, we would get:

```
<div itemscope="" itemtype="http://schema.org/Movie"></div>
```

it would be great to allow bleach to somehow handle boolean attributes.

maybe accept a list of what should be kept as a key-only, and what should be handled as a `key="key"` pairing.

**Comment by jvanasco** [comment]
After digging into things, this appears to be an issue in html5lib (https://github.com/html5lib/html5lib-python/issues/194)

by default it should minimize boolean attributes - however it has its own list of boolean attributes.

**Comment by willkg** [comment]
I don't think there's anything I can do in Bleach to alleviate this without a lot of work. I see you wrote up a PR in html5lib:

https://github.com/html5lib/html5lib-python/pull/327

Now that Bleach supports html5lib >= 0.99999999 (8 9s), then as soon as they land that and do a release, you're good to go.

Given that there's nothing we're going to do here, I'm going to close this out.
