### ISSUE TITLE
How to use bleach/html5lib with defusedxml

### ISSUE THREAD

**Issue by graingert** [mozilla/bleach#158]
[defusedxml](https://pypi.python.org/pypi/defusedxml) is a library that provides safe defaults for xml library configuration.

It would be useful to include documentation on how to use bleach with a parser that has been configured with [defusedxml](https://pypi.python.org/pypi/defusedxml).

**Comment by willkg** [comment]
@graingert Can you do this work? If not, I don't understand it well enough to do it so it's likely this issue will just sit around forever.

**Comment by graingert** [comment]
Looks like this might be an issue for html5lib?

**Comment by mdxs** [comment]
From @gsnedders response to https://github.com/html5lib/html5lib-python/issues/266, I would conclude that this issue can be closed for bleach.

**Comment by willkg** [comment]
Ok--closing this out.
