### ISSUE TITLE
Are paragraphs really unsafe?!

### ISSUE THREAD

**Issue by Kwpolska** [mozilla/bleach#174]
Markdown got me here.  This looks plain crazy:

```python
>>> import bleach
>>> bleach.clean('<p>hello</p> <ul>hi</ul>')
'&lt;p&gt;hello&lt;/p&gt; <ul>hi</ul>'
```

**Comment by willkg** [comment]
I think the underlying question is the wrong one to be asking. It's not "Bleach thinks these tags are unsafe", but more "Bleach doesn't think this tag should be in the extremely minimal set of tags".

Bleach allows a very minimal set of tags by default and you need to explicitly whitelist the ones you want to allow.

This doc might help:

http://bleach.readthedocs.org/en/latest/goals.html#sanitizing-input

Hope that helps!

**Comment by Kwpolska** [comment]
Thanks for the info!
