### ISSUE TITLE
Drop bleach.encoding module

### ISSUE THREAD

**Issue by jsocol** [mozilla/bleach#176]
`bleach.encoding` is a 63 line file that has a single meaningful function that is used [once](https://github.com/mozilla/bleach/blob/16551353ef6edc00d48f81ded4b4b6e030f910ed/bleach/__init__.py#L104). The only time `force_unicode` is used is to ensure that the input to `clean` is `six.text_type` instead of bytes. It includes all sorts of [weird](https://github.com/mozilla/bleach/blob/16551353ef6edc00d48f81ded4b4b6e030f910ed/bleach/encoding.py#L55-L59), [unused](https://github.com/mozilla/bleach/blob/16551353ef6edc00d48f81ded4b4b6e030f910ed/bleach/encoding.py#L32) paths and handles old Django types that aren't even used by Django anymore.

I think the entire module could be replaced by using `six.text_type` on [`__init__.py:104`](https://github.com/mozilla/bleach/blob/16551353ef6edc00d48f81ded4b4b6e030f910ed/bleach/__init__.py#L104) (though `linkify()` doesn't have that call, so maybe linkify _should_, or maybe clean doesn't need it?).

**Comment by willkg** [comment]
Putting this in the 2.0 milestone for now since we're dropping support for a bunch of things in that milestone and can probably more easily do this.

**Comment by willkg** [comment]
I'm dropping this from the milestone. I think it needs more thinking, but I'm not going to get to it for 2.0.

**Comment by willkg** [comment]
We recently adjusted linkify and clean to throw a `TypeError` if the argument is not a text type. So, I think we can nix the module now since now it's not doing anything.

**Comment by willkg** [comment]
Oh, wait--actually it is still converting str -> unicode for Python 2 cases. I'll look into this further and probably clean it up for 2.1.
