### ISSUE TITLE
How to remove empty tags

### ISSUE THREAD

**Issue by brijeshb42** [mozilla/bleach#177]
Suppose I have this html:
```<p>Hello <b> </b><em>World</em>. <strike></strike> Hi</p>```

How I can I get the output after removing tags that are empty or have only spaces:
__Output__ : ```<p>Hello <em>World</em>.  Hi</p>```

**Comment by willkg** [comment]
I don't think this is something bleach can do. Further, I'm not sure this is something that bleach should grow the ability to do. I can't see a compelling argument for how this kind of alteration makes arbitrary text safer. If you can think of one, I'd like to discuss it.

I think your best bet is to use html5lib or Python's built-in HTMLParser and walk the tree to do the transform. This part of the html5lib docs might be relevant:

http://html5lib.readthedocs.org/en/latest/movingparts.html#tree-walkers

Hope that helps!
