### ISSUE TITLE
Make linkify extensible 

### ISSUE THREAD

**Issue by defrex** [mozilla/bleach#181]
URLs and Email addresses are two types of things you might want to linkify, but they aren't the only things. For example, in #178 I extended it to linkify hashtags. Other things like Issues and PRs on GubHub, or any other application-specific thing one could think of, could all benefit from `bleach.linkify`.

An API could look something like this:

``` Python
import re
import bleach

hashtag_re = re.compile(r'#([\w\-_]+)', re.IGNORECASE | re.MULTILINE)


def hashtag_handler(re_match):
    tag = re_match.group(1)
    return {
        '_text': '#{}'.format(tag),
        'href': '/itemlist/?tag={}'.format(tag),
    }


bleach.linkify(input, extra_types=(
    (hashtag_re, hashtag_handler),
))
```

**Comment by willkg** [comment]
I've thought about this and I see the utility, but it's not something I want to implement in Bleach.

However, I just rewrote linkify as an html5filter. That'll go out with Bleach 2.0. Using that, you can hang another filter off of that and implement whatever kind of additional linkifying you want to do.

Given that, I'm going to close this out.

**Comment by psychomantys** [comment]
Theres a example link for this on bleach 2.0?

**Comment by willkg** [comment]
@psychomantys Maybe these help?:

* https://bleach.readthedocs.io/en/latest/linkify.html#using-bleach-linkifier-linkifyfilter
* https://html5lib.readthedocs.io/en/latest/movingparts.html#filters
* reading the html5lib code for filters

**Comment by psychomantys** [comment]
Uhum, i need to implement a filter on html5lib?

Is more easy to use a regex on the text before linkify it?

**Comment by willkg** [comment]
Yes, you need to write a html5lib Filter. You can use regexes in them--that'd be fine. If you don't like that, you can call linkify and then run your regex on the string output. Lots of options!

**Comment by psychomantys** [comment]
Thanks!! ^^
