### ISSUE TITLE
Add option to remove content inside of stripped tags

### ISSUE THREAD

**Issue by dangayle** [mozilla/bleach#185]
Currently, if you have a block of html with a javascript `<script>` tag within it, you can strip the _tag itself_, but not the actual javascript.

```
>>> import bleach
>>> test = '<div><p>A test</p><script>console.log("test")</script></div>'
>>> bleach.clean(test, strip=True)
u'A testconsole.log("test")'
```

It would be nice if we could strip all of the javascript out of the text entirely.

**Comment by mclate** [comment]
+1
Noticed that bleach ignores data within `iframe` tag:
```python
>>> import bleach

>>> data = """<script>alert("first");</script> <span><script>alert("second")</script></span>"""
>>> bleach.clean(data, tags=bleach.ALLOWED_TAGS + ['span'])
u'&lt;script&gt;alert("first");&lt;/script&gt; <span>&lt;script&gt;alert("second")&lt;/script&gt;</span>'

>>> data = """<script>alert("first");</script> <iframe><script>alert("second")</script></iframe>"""
>>> bleach.clean(data, tags=bleach.ALLOWED_TAGS + ['iframe'])
u'&lt;script&gt;alert("first");&lt;/script&gt; <iframe><script>alert("second")</script></iframe>'
```
It would make sense to be able to remove content within `iframe` tag

**Comment by willkg** [comment]
@mclate I think the issue here is that tags are removed, but not the contents of those tags. Your issue seems to be that tags aren't being removed if they're children of iframe tags.  I think that's a different issue. Can you open a new issue for it?

**Comment by w121211** [comment]
+1, needs such function

**Comment by calvin** [comment]
@willkg: @aysonje has a pull request that addresses this issue. Can you have a look if you have a chance?

**Comment by jaap3** [comment]
This seems similar to #67.

In the discussion for that ticket it's noted that it would be useful to be able to supply a list of tags of which the content should be stripped. 

In the pull request related to this ticket all the content of disallowed tags is stripped. This behaviour seems less useful to me. The common use case would be to strip the content of script and style tags but to keep the rest, regardless if the tags they are surrounded with are allowed or not.

**Comment by willkg** [comment]
I've thought about this for a while and I think I'm going to pass on it for `.clean()`.

There are two big reasons for doing this:

1. `.clean()` is about removing malicious content--not about transforming HTML documents for other mediums or prettifying content. `.clean()` is a security-focused function and as such, keeping its functionality minimal reduces the likelihood of bugs that have security-related impact. That's really important.
2. Seems like the use cases for stripping content in tags are related to transforming HTML documents and prettifying content. I think that should get handled by a different function or possibly not by bleach at all.

Towards that, I've clarified the goals/non-goals language and updated the docs to make it clearer what `.clean()` is supposed to be doing and what it's not going to be good for.

Given that, I'm going to pass on this and close it out.

I'm game for talking about building a `.prettify()` function which is about prettifying HTML which would cover the use these changes cover. That should be a new issue, though.
