### ISSUE TITLE
Unable to install bleach on Python 2.7.10 by both Git and easy_install methods

### ISSUE THREAD

**Issue by bjornlee555** [mozilla/bleach#189]
When i tried the Git method: i get this error... 
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory

When i tried the easy_install method, i get below...

Extracting bleach-1.4.2-py2.7.egg to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Adding bleach 1.4.2 to easy-install.pth file
error: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/easy-install.pth'

**Comment by willkg** [comment]
Are you able to install other packages from PyPI?

**Comment by willkg** [comment]
I suspect this is more of a support issue than a bug given that no one else has piled onto this issue.

I'm going to close this out for now since there's been no reply to my question from February. If you're still having problems, feel free to add another comment and I can try to help out.
