### ISSUE TITLE
html5lib update

### ISSUE THREAD

**Issue by mgilson** [mozilla/bleach#196]
It looks like an [update to `html5lib`](https://github.com/html5lib/html5lib-python/pull/110/files) is going to break this project once it is released.  At least, I tried the latest html5lib and bleach wouldn't import:

```py
>>> sys.path.insert(0, PATH_TO_NEW_HTML5LIB)
>>> import bleach
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/bleach/__init__.py", line 13, in <module>
    from .sanitizer import BleachSanitizer
  File "/Library/Python/2.7/site-packages/bleach/sanitizer.py", line 11, in <module>
    PROTOS.remove('feed')
AttributeError: 'frozenset' object has no attribute 'remove'
```

I don't think there is any problem yet as `html5lib` hasn't actually released the latest version (as far as I'm aware), but I figured that I'd let you know so you can get ahead of this one...

**Comment by willkg** [comment]
This is covered by #195. Thank you for the heads-up!
