### ISSUE TITLE
unify version information

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#197]
Currently, the version is in three separate files:

1. `setup.py`
2. `docs/conf.py`
3. `bleach/__init__.py`

That's annoying plus if you look at past releases, it's clear we miss one periodically.

This bug covers moving the version into `bleach/__init__.py` and changing the other two to look there for the version.

**Comment by TimDumol** [comment]
I tried tackling this here: https://github.com/mozilla/bleach/pull/198. Hope it's good enough!

**Comment by willkg** [comment]
This was fixed with #198. Closing it out. Thank you @TimDumol !
