### ISSUE TITLE
linkify doesn't detect URLs which use new top level domains

### ISSUE THREAD

**Issue by egnor** [mozilla/bleach#201]
```
>>> import bleach
>>> bleach.linkify('http://oskibearsin.com/')
u'<a href="http://oskibearsin.com/" rel="nofollow">http://oskibearsin.com/</a>'
```

... great ...

```
>>> bleach.linkify('http://oskibearsin.space/')
u'http://oskibearsin.space/'
```

... not good, since this is a totally valid domain name! I'm actually a little surprised that linkify won't accept any domain in an otherwise well-formed HTTP URL; this will fail to linkify unqualified intranet URLs:

```
>>> bleach.linkify('http://myintranet/')
u'http://myintranet/'
```

/cc @jschwab

**Comment by willkg** [comment]
I just wrote up #223 which covers the underlying issue behind this. I'm going to close this issue in favor of that one.
