### ISSUE TITLE
set up auto-push-to-pypi via travis

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#209]
Jazzband and other projects have a setup where you tag the code, it gets tested by travis and then that gets pushed to pypi.

We should do that for bleach, too. Then we don't have to worry about everyone having admin access on pypi.

**Comment by willkg** [comment]
@jezdez Did you set this up for jazzband? Can you set it up here, too?

**Comment by jezdez** [comment]
@willkg Sure thing, it's mostly [following the docs](https://docs.travis-ci.com/user/deployment/pypi). I'll do it now

**Comment by willkg** [comment]
Oh, that's super helpful! I had no idea those docs existed.

Thank you @jezdez!
