### ISSUE TITLE
Not Wanted lowercases

### ISSUE THREAD

**Issue by Vorlif** [mozilla/bleach#216]
Hello everyone. Thank you for your good package!

Unfortunately, I have a small problem.
If I use `bleach.clean('<ThisIsATest>')` it will be output `&lt;thisisatest&gt`.
Is there a way that the letters between the brackets will not be written mall?

**Comment by willkg** [comment]
I'm not sure I understand why it matters that `.clean()` changes the case for HTML tags.

Why is this a bad thing for you?

**Comment by Vorlif** [comment]
I nedd the content of the tag (``ThisIsATest``) as he is.

But after ``.clean()`` he is lowercase.

**Comment by Vorlif** [comment]
I understand that the program is not thought for it. 
Therefore I close this issue.

Thanks you for your time willkg.
