### ISSUE TITLE
clean.html docs incomplete

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/bleach#237]
https://github.com/mozilla/bleach/blob/37431401bcd8e37209fdca9235289a8c1fb3877e/docs/clean.rst#stripping-comments

```
import bleach

bleach.clean(u"<em>I'm so <strong>important</strong>!</em>", strip=True)
```
should work, but the tags are listed in [ALLOWED_TAGS](https://github.com/mozilla/bleach/blob/37431401bcd8e37209fdca9235289a8c1fb3877e/bleach/__init__.py#L30), hence it does nothing.

You need to pass `tags=[]` to the function call in order to get rid of all HTML tags.

**Comment by willkg** [comment]
Yeah... I can see what you're getting at. It's not particularly clear that `strip` changes what `bleach.clean` does for tags not in the tags whitelist.

I'll fix that.

**Comment by willkg** [comment]
Thank you!
