### ISSUE TITLE
Support regex for allowed tags

### ISSUE THREAD

**Issue by gomezjdaniel** [mozilla/bleach#238]
Hello,

I am using bleach to escape the input of a create article page. Thing is I am supporting markdown as an input and therefore I allow to enter pieces of code. Problem is if I enter a piece of C code which says `#include <thethingsnetwork.h>` it will be escaped by bleach. Is there any possibility to add as allowed tags a regex?

**Comment by willkg** [comment]
I think you're using bleach in a way that's not going to work. Bleach operates on HTML--not on Markdown. I think you have a couple of options:

1. Convert the Markdown string to HTML and then have bleach operate on that.
2. Parse the Markdown and have bleach operate on parts of it that don't contain HTML-like things.

Of the two, I think you'll have most success with the first one.

Hope that helps!
