### ISSUE TITLE
verify sanitizated output for regression tests

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#242]
In pull #241, I added regression tests for `bleach.clean`. We should verify the output for those regression tests.

**Comment by willkg** [comment]
Tagging @g-k with this one.

**Comment by g-k** [comment]
👍 I'm planning to pull in the test page from https://cure53.de/purify and modify it to POST to a test server that calls `bleach.clean` and plugs the result back into the DOM.

Hopefully we can reuse their karma test runner to easily check against browsers too: https://github.com/cure53/DOMPurify/blob/master/test/karma.conf.js

**Comment by willkg** [comment]
The output is probably fine.
