### ISSUE TITLE
don't hardcode pytest version

### ISSUE THREAD

**Issue by ignatenkobrain** [mozilla/bleach#244]
Having `==3.0.3` doesn't make any sense and creates problem for packaging.

**Comment by willkg** [comment]
pytest is only in the `requirements.txt` file which is intended for developers or people hacking on bleach to set up an environment for development. I'm not sure why pinning versions in that file (which helps development) affects packaging for users.

Can you elaborate?

**Comment by willkg** [comment]
I'm not sure what the issue is here, so I'm going to close it out.
