### ISSUE TITLE
Dublicates in email_re

### ISSUE THREAD

**Issue by tonal** [mozilla/bleach#247]
Line https://github.com/mozilla/bleach/blob/master/bleach/__init__.py#L81 and https://github.com/mozilla/bleach/blob/master/bleach/__init__.py#L82 - duble symbol "!" in symbol classes

Line https://github.com/mozilla/bleach/blob/master/bleach/__init__.py#L84 - dubles symbol "1" in symbol class. My be forget "\"

**Comment by willkg** [comment]
Hi! I don't really understand this issue report. Are you reporting a bug or suggesting code changes or what? Can you elaborate?

**Comment by tonal** [comment]
Also see http://emailregex.com/

**Comment by willkg** [comment]
This is fixed in #264.
