### ISSUE TITLE
look at alternatives to htm5lib

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#255]
lxml has a `clean`:

http://lxml.de/lxmlhtml.html#cleaning-up-html

It can also autolink.

It's worth finding or creating a comparison between bleach's `clean` and `linkify` and lxml.html's `clean` and `autolink`.

**Comment by belak** [comment]
It's also much faster. I was looking at this a while ago, but bleach was pretty coupled with html5lib.

**Comment by willkg** [comment]
There's also this project: https://html5-parser.readthedocs.io/en/latest/

It doesn't look like it has a critical mass as a project, yet.

**Comment by minusf** [comment]
Just a note: lxml's style removal is binary: all or nothing.

However micromanaging the allowed style properties can be very time consuming, and actually i wish `bleach` could deal with a wild card (but as `html5lib` can't, `bleach` also can't).

The actual whitelist inside `html5lib` is much longer (https://github.com/html5lib/html5lib-python/blob/master/html5lib/filters/sanitizer.py#L555) and of course there is https://github.com/html5lib/html5lib-python/issues/317 which i guess is also a `bleach` bug/undocumented feature.

**Comment by willkg** [comment]
> However micromanaging the allowed style properties can be very time consuming, and actually i wish bleach could deal with a wild card (but as html5lib can't, bleach also can't).

If this is something you're interested in, you should write up an issue for it.

> The actual whitelist inside html5lib is much longer (https://github.com/html5lib/html5lib-python/blob/master/html5lib/filters/sanitizer.py#L555) and of course there is html5lib/html5lib-python#317 which i guess is also a bleach bug/undocumented feature.

Bleach has its own `sanitize_css` that's not affected by html5lib's version. I'm not really sure what you mean by "bug/undocumented feature" here. Is there a problem with Bleach that you're thinking about here?

**Comment by minusf** [comment]
my bad, i haven't noticed the overriding of `sanitize_css`. Is there a specific reason they are unwilling to fix their version? Is there a reason their initial whitelist is not good for `bleach`?

What is the story behind the empty whitelist for style? All other `ALLOWED_*` settings come at least with some minimal defaults.  What is the point of allowing a `style` tag when everything in it is thrown away?

**Comment by willkg** [comment]
I think talking about design decisions and user support is getting off topic for this issue. If you want to chat, hop on IRC. We hang out on `#bleach` on irc.mozilla.org. Alternatively, you could open up separate issues for the problems you're having. Sorry about that!

**Comment by willkg** [comment]
We vendored html5lib. I think that's good enough for now.

**Comment by belak** [comment]
My reason for preferring another library is that html5lib is comparatively prohibitively slow. Especially when compared to lxml.

What was the main reason for deciding to drop this?

**Comment by willkg** [comment]
The primary (unwritten) reason I wrote up this bug was that html5lib was difficult to support and seemed unmaintained. Since then, I pushed out a 1.0 which solved a bunch of issues and then I vendored it in Bleach so my issues weren't really an issue anymore.

If you're interested in alternatives to html5lib, you're welcome to spend some time on it. I'd love to know what you drum up!
