### ISSUE TITLE
bleach doesn't work with html5lib==1.0b8

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#268]
html5lib has two sets of version numbers that are equivalent to one another. html5lib 1.0b8 is the same as 0.9999999 (7 9s).

Users who are using html5lib 1.0b8 and upgrade Bleach to 2.0 and don't also explicitly upgrade to html5lib 1.0b9 or later end up in a busted state because pip doesn't know that html5lib 0.99999999 (8 9s) is not before 1.0b8.

This issue covers adding a note in the docs about that.

Further, if we can fix the version requirements in `setup.py` somehow to force pip to correctly upgrade html5lib to correct versions, that'd be cool. That's worth a 2.1 release.

**Comment by willkg** [comment]
I made a change to CHANGES to cover the whole 1.0b8 problem. Going to tag this issue with a needs-your-help and hopefully someone shows up and submits a PR.

**Comment by ibrahimsharaf** [comment]
Hello @willkg, I want to work on this issue, can you guide me on how to begin?

**Comment by willkg** [comment]
This page:

http://bleach.readthedocs.io/en/latest/dev.html

covers installing Bleach and some other things for development.

I think you're going to have to mess around with this line:

https://github.com/mozilla/bleach/blob/master/setup.py#L19

I don't know how to specify two sets of independent predicates for versions. Maybe it's not possible? That could use some research.

Maybe the best solution here is to keep what's there, but add a bunch of "and not 1.0b1 and not 1.0b2 and not 1.0b3 ..." for all the 1.0bx that aren't supported? Maybe a good first step is to see how many versions there are and if it's a short list, then this option is pretty viable?

**Comment by ibrahimsharaf** [comment]
Yes, it certainly does!
I'll start digging and will keep you updated.

**Comment by willkg** [comment]
You rock! I really appreciate it. Feel free to ping me if you have questions.

**Comment by willkg** [comment]
This is fixed in #284.
