### ISSUE TITLE
clean escapes tags found in a <script> even if they're allowed

### ISSUE THREAD

**Issue by GevatterGaul** [mozilla/bleach#270]
In bleach 1.5.0 clean would only filter not allowed tags:
```
>>> from bleach import clean
>>> clean('<script><b>Hello</b></script>', ['b'])
'&lt;script&gt;<b>Hello</b>&lt;/script&gt;'
```
bleach 2.0 doesn't honor the allowed tag when there are other tags:
```
>>> clean('<script><b>Hello</b></script>', ['b'])
'&lt;script&gt;&lt;b&gt;Hello&lt;/b&gt;&lt;/script&gt;'
>>> # But:
>>> clean('<b>Hello</b>', ['b'])
'<b>Hello</b>'

```

**Comment by willkg** [comment]
If you swap b and script, it works:

```
>>> bleach.clean('<b><script>foo</script></b>', tags=['b'])
u'<b>&lt;script&gt;foo&lt;/script&gt;</b>'
```

And also with non-script tags:

```
>>> bleach.clean('<em><b>foo</b></em>', tags=['b'])
u'&lt;em&gt;<b>foo</b>&lt;/em&gt;'
```

I think what you're seeing is because `<script>` isn't allowed to have tags in it:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

Are you having problems with other tag combinations or just `<script>`?

**Comment by GevatterGaul** [comment]
I didn't try other combinations.

**Comment by willkg** [comment]
Can you tell me more about the context? Why is this a problem for you?

**Comment by GevatterGaul** [comment]
This is not really a problem for us as we can work around the order problem. It just didn"t work when we tried it.

**Comment by willkg** [comment]
Ok. Given that, I'm going to close this out.

Thank you for reporting!
