### ISSUE TITLE
Documentation issue - conflicting information on html5lib version support

### ISSUE THREAD

**Issue by twhetzel** [mozilla/bleach#272]
In the document here: https://bleach.readthedocs.io/en/latest/changes.html, at the top of the page it says "Bleach no longer supports html5lib < 0.99999999 (8 9s)." And also says "If you’re using 0.9999999 (7 9s) upgrade to 0.99999999 (8 9s) or higher."

However, further down under the section "Changes" it also says "Supports html5lib >= 0.99999999 (8 9s)."

**Comment by willkg** [comment]
I don't see what's conflicting about that. Can you elaborate?

**Comment by twhetzel** [comment]
Apologies, I misread the information.

**Comment by willkg** [comment]
If you think the language could use work to make it less confusing, let me know. I'm definitely game for improving it.
