### ISSUE TITLE
Support whatsapp protocol in href attribute of `a` tag

### ISSUE THREAD

**Issue by rohit-taneja** [mozilla/bleach#276]
version 1.4.2

Currently

```
bleach.clean("<a href=whatsapp://send?text=Hello>Call to Whatsapp</a>")
```

is Giving Result:

```
<a>Call to Whatsapp</a>
```

**Comment by willkg** [comment]
1.4.2 is a while ago. I highly encourage you to upgrade to at least Bleach 1.5. That version allows you to set the list of allowed protocols which would let you support this.

http://bleach.readthedocs.io/en/latest/changes.html#version-1-5-november-4th-2016

http://bleach.readthedocs.io/en/latest/clean.html#allowed-protocols-protocols

Does that help?

**Comment by rohit-taneja** [comment]
@willkg That worked. Thanks 👍
