### ISSUE TITLE
tags get added when tokenizing with bleach 2.0

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#280]
When I redid Bleach to support html5lib >= 0.99999999 (8 9s), I rewrote the sanitizing code to operate as an html5lib filter rather than as a tokenizer. The result of this is that the tokenizer cleans up the HTML before Bleach gets a chance to work on it and the act of cleaning up the HTML sometimes changes or creates new tags.

I wrote up this issue: https://github.com/html5lib/html5lib-python/issues/312

For example, if you had:
```
import bleach
bleach.clean('Yeah, sure. <sarcasm/>', strip=False)
```
it'd get turned into:
```
'Yeah, sure. &lt;sarcasm&gt;&lt;/sarcasm&gt;.'
```
and then that'd get escaped/dropped/whatever.

Adding this as an issue to help catch other regressions and use cases so I can figure out if I want to spend more time looking into a fix.

**Comment by gavinwahl** [comment]
This effects me because I run the output of a markdown renderer through bleach. 

Markdown turns an input of `<http://example.com/>` into a link, <http://example.com/>. The issue occurs when users mess up the syntax and input something like `<example.com>`. This does not get turned into a link, but is passed through the markdown renderer unchanged. Bleach then mangles it and the user ends up getting an output of `<example.com></example.com>`.

**Comment by ThiefMaster** [comment]
I think the 2.0 behavior is pretty bad and should be changed as soon as possible in a 3.0 release.

```
>>> import bleach
>>> bleach.clean('randomdude <dude@example.com>')
u'randomdude &lt;dude@example.com&gt;&lt;/dude@example.com&gt;'

>>> bleach.clean('<http://example.com>')
u'&lt;http: example.com=""&gt;&lt;/http:&gt;'
```

I don't think this is what anyone wants...

**Comment by willkg** [comment]
@ThiefMaster @gavinwahl I haven't had time to work on this.

Pretty sure this is going to require overriding parts of the html5lib tokenizer to know about the allowed-tags list.

Anything you can do to move this forward would be super! Otherwise it's going to sit around until I have time or someone else spends time on it.

**Comment by pattisdr** [comment]
Hello! We're in the process of upgrading bleach, and also noticing odd behavior around tags being added:

Simple example:
<img width="700" alt="screen shot 2017-12-21 at 2 49 22 pm" src="https://user-images.githubusercontent.com/9755598/34274467-5745f7d8-e65e-11e7-901f-3ff0ff63a16c.png">

More specifically, we are seeing this:
```
'<p>Xiv: <script>Support</script> | <pre>Contact<pre> | <a href=""><span class="fa fa-facebook"></span></a></p>'
```
getting turned into this:
```
'<p>Xiv: Support | </p>Contact | <a href=""><span class="fa fa-facebook"></span></a><p></p>'
```

**Comment by willkg** [comment]
@pattisdr Oo--that's a tricky one! What's going on is that `<pre>` is not a valid child of `<p>`, so html5lib adds the `</p>` before the `<pre>` and the `<p>` after the `</pre>`. Then after html5lib is done tokenizing, Bleach 2+ removes the `<pre>` and `</pre>` tags.

Pretty sure fixing this involves overriding parts of the html5lib tokenizer to know about the allowed-tags list so that it can do something different. I'm happy to help someone look into this, but probably won't have time to spend on this myself for a while.

**Comment by pattisdr** [comment]
ah, I see, thanks for the quick response @willkg!

**Comment by Deimos** [comment]
@willkg I saw you mention somewhere else that this would be a good place to post examples of how the tag-closing behavior is a problem. In my case, I'm using Bleach to sanitize the HTML (after Markdown parsing) from user posts/comments. It's pretty common for people to write a comment using angle brackets around a "marker" like:

> Please write your responses in this format: "Favorite movie: <name>", thanks.

html5lib seems to be "fixing" these, even if they're not valid HTML tags. The result from running a comment like that through `clean()` is:

> Please write your responses in this format: "Favorite movie: <name>", thanks.</name>

It's even worse if they include spaces, like `<name of movie>`:

> Please write your responses in this format: "Favorite movie: <name movie="" of="">", thanks.</name>

Do you think it's feasible at all to be able to disable this behavior? I could try to help with it, if needed.

**Comment by willkg** [comment]
@ThiefMaster @gavinwahl @Deimos @pattisdr: I just landed some changes that fix the regressions mentioned in this issue.

Can you take some time and test those out with the data you were having problems with in the next few days?

You can get a zipfile of master tip that has the changes here: https://github.com/mozilla/bleach/archive/master.zip

**Comment by Deimos** [comment]
@willkg the changes do seem to fix `bleach.clean()`, however `bleach.linkify()` still causes the same issues. I'm running text through `linkify()` and then later through `clean()`, so in the end it still produces the same result.

Is it possible to fix `linkify()` in the same way as `clean()` was?

**Comment by Deimos** [comment]
Sure, if you'd like. From a quick glance, it looks like `linkify()` uses an html5lib filter too, so if that was the  cause of the issue in `clean()` it might be fairly similar. I'll make an issue though.

**Comment by sneakers-the-rat** [comment]
Got redirected here from https://github.com/mozilla/bleach/issues/285

Still an issue when used with a markdown parser for cases of mixed input where one puts markdown in between html tags. 

e.g. as one would do in a github issue like

<details>
<summary>expand/collapse</summary>

```python
a = 1 + 1
```

</details>

with

````
<details>
<summary>expand/collapse</summary>

```python
a = 1 + 1
```

</details>
````

the parser receives the html fragment

```
<details>
<summary>expand/collapse</summary>
```

as one block and the closing tag as the other, but when applied to each of them yields

```
<details>
<summary>expand/collapse</summary>
</details>

(inner markdown content)

<details></details>
```

**Comment by willkg** [comment]
@sneakers-the-rat Please open up a new issue with steps to reproduce.
