### ISSUE TITLE
Should bleach balance disallowed tags?

### ISSUE THREAD

**Issue by jeffoneill** [mozilla/bleach#281]
Hello, sorry if this has been addressed before but I couldn't find it anywhere...

This is current behavior:

`bleach.clean("<script>")`
`u'&lt;script&gt;&lt;/script&gt;'`

It seems weird to balance a tag that is not allowed.  Wouldn't it make more sense for the output to be:

`u'&lt;script&gt;'`

Though I suppose that even if that would be preferred behavior that it might be a complicated change...

**Comment by willkg** [comment]
Hi! This is sort of covered in #280. The general problem being that the html5lib tokenizer fixes the HTML before Bleach has a chance to strip/escape unwanted tags during sanitization.

Can you add a comment in #280 about this? Particularly if you have real examples that aren't junk text? 

Thank you!
