### ISSUE TITLE
Stripping links with invalid protocols results in empty links

### ISSUE THREAD

**Issue by grote** [mozilla/bleach#288]
When bleach encounters a protocol that is not allowed, it strips it as expected. However, it leaves an empty `<a/>` tag behind:

```python
>>> import bleach
>>> bleach.clean('<a href="test://bla">empty link</a>', strip=True)
'<a>empty link</a>'
```

I would expect it to strip away the tag completely.

**Comment by willkg** [comment]
I can see why you would expect that, but I think that change cause Bleach to change the structure of the document in an unexpected way and I don't want to add more configuration to enable/disable that kind of behavior.

Instead, you should write an html5lib filter and have that run after Bleach's sanitization filter. That filter would remove empty `<a>` tags.

See these docs for inspiration: http://bleach.readthedocs.io/en/latest/clean.html#html5lib-filters-filters

Does that help?

**Comment by grote** [comment]
Thanks for the tip!

I don't really know anything about `html5lib` filters, so I leave the one I came up with here, so it might help others and for more knowledgable people to point out the bugs in mine:

```python
class EmptyLinkFilter(Filter):
    def __iter__(self):
        remove_end_tag = False
        for token in Filter.__iter__(self):
            # only check anchor tags
            if 'name' in token and token['name'] == 'a' and token['type'] in ['StartTag', 'EndTag']:
                if token['type'] == 'StartTag' and token['data'] == {}:
                    remove_end_tag = True
                    continue
                elif token['type'] == 'EndTag' and remove_end_tag:
                    remove_end_tag = False
                    continue
            yield token
```

**Comment by willkg** [comment]
I think this is worked out, so I'm going to close it out.
