### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by erwinyusrizal** [mozilla/bleach#289]
Hi, I have this error when running
```
allowed_tags = ['a', 'abbr', 'acronym', 'b', 'em', 'i', 'li',
                        'ol', 'strong', 'ul', 'h1', 'h2', 'h3', 'h4', 'h5', 'p']
target.policy = bleach.clean(
            value, tags=allowed_tags, strip=True
)
```
I see it's fixed here https://github.com/mozilla/bleach/issues/69

I use bleach v2.0.0, any idea to fix it?

Thanks

**Comment by willkg** [comment]
There's an error that's fixed in linkify in #69, but clean and linkify don't overlap.

Can you copy the traceback in a comment? Maybe skip some of the repeating bits?

Also, what version of Python and html5lib are you using? And what's a representative value for `value` above?

**Comment by erwinyusrizal** [comment]
@willkg I fixed this, the propblem was came from SQLAlchemy on 'SET' event listener

`maximum recursion depth exceeded while calling a Python object`

but for now I move it on my views directly and it works

Thanks for your response

**Comment by willkg** [comment]
Glad you could fix it! :)
