### ISSUE TITLE
Allowed tags are changed/deleted

### ISSUE THREAD

**Issue by joe42** [mozilla/bleach#290]
The problem occurs inside the html5lib you use. For instance, the following code will strip the caption elements:

`html5lib.serialize(html5lib.parseFragment(‘<caption>x</caption>‘))`

Smallest "not" working example:

```
import bleach
tags = [
        'a',
        'blockquote',
        'br',
        'caption',
        'del',
        'div',
        'em',
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'header',
        'hr',
        'img',
        'li',
        'ol',
        'p',
        'span',
        'strong',
        'sub',
        'sup',
        'table',
        'tbody',
        'td',
        'tfoot',
        'th',
        'thead',
        'tr',
        'u',
        'ul',
    ]
bleach.clean("<br></br><caption></caption><tbody></tbody><td></td><tfoot></tfoot><th></th><thead></thead><tr></tr>", tags, [], [])
```

This will produce 

> `<br><br>`

The expected result should show the complete input string without modifying it.

**Comment by joe42** [comment]
It would be great if you could create a patch for this. 

Keep up the good work!

**Comment by willkg** [comment]
What version of bleach, html5lib, and Python are you using?

**Comment by joe42** [comment]
Python 2.7.12
bleach 1.4.3
bleach.html5lib 0.9999999

**Comment by joe42** [comment]
Except for the problem with the br tag, the other tags get deleted because they are not surrounded by the correct context in my example. For instance, the caption tag is not filtered when it is surrounded with table tags.

**Comment by willkg** [comment]
Looking at your example again, other than `<br>` none of the tags in your example are valid HTML.

I'm not sure what this bug is about, then. One of the things that html5lib does is correct the HTML by dropping, moving, and adding tags and fixing quoting and other things so that it's valid HTML. Seems like you want Bleach to just add/remove tags, but not bother with producing valid HTML. Is that right?

**Comment by joe42** [comment]
@willkg: I just noticed my fault. See my comment above. Thanks a lot for your help.

**Comment by willkg** [comment]
No worries! Thank you for reporting!
