### ISSUE TITLE
Cleaned URLs contains HTML entities

### ISSUE THREAD

**Issue by mmtr** [mozilla/bleach#291]
When cleaning an URL having a parameter that contains an HTML name, the sanitized URL will contain the HTML entity.

```
import bleach
bleach.clean('http://example.com?active=true&current=true')
# Out: u'http://example.com?active=true\xa4t=true'
```

**Comment by willkg** [comment]
Hi! I need some more details before I can understand the context of this issue.

What version of bleach, html5lib, and python are you using?

What did you expect to happen in this case?

**Comment by mmtr** [comment]
Thanks for the quick response!

We're using bleach 1.4.3, html5lib 0.99 and python 2.7.6.

As the URL doesn't contain any HTML entity I expect to have the same URL I have entered

**Comment by willkg** [comment]
This looks like a variant of issue #143. I'm going to add the description there and close this one out.

Thank you for reporting!

**Comment by jvanasco** [comment]
This is actually different, but related.  Digging into this library and stdlib:

The #143 ticket is that HTML entities are unescaped into unicode, but not encoded back into HTML entities.

The #291 ticket looks to be a bug with certain Python libraries, including the `unescape` function in the Python 2.7.x and 3.5.x standard html parsing libraries.  The HTML5 spec requires named entities to terminate with a semicolon to avoid "fragile constructs".  the standard library functions don't respect the required ";" rule, and `&current` is being interpreted as `&curren` + `t` to create `\xa4t`.  the html5lib and xml.sax.utils libraries both enforce the trailing ';' rule. I haven't been able to pinpoint where this is being incorrectly escaped yet.

**Comment by willkg** [comment]
@jvanasco `&curren` is getting converted to unicode because it's in the entities map in html5lib:

https://github.com/html5lib/html5lib-python/blob/984f934d30ba2fde0e9ce5d4581c73fb81654474/html5lib/constants.py#L1560

The entities map includes entities with and without the semicolon.
