### ISSUE TITLE
bleach.linkify(None) returns u'None'

### ISSUE THREAD

**Issue by overfl0** [mozilla/bleach#292]
It looks like linkify is doing a repr(argument) somewhere in its code because I can pass it some other type arguments, like `int` (or even `type(int)` for extra amusement :) )

`bleach.clean(None)`, on the other hand, returns `u''` which is a more sensible of an answer.

However, for both of those functions, I would expect to either raise an exception or to return None, instead of returning an unicode string.

bleach==2.0.0
html5lib==0.999999999 (nine 9)

**Comment by willkg** [comment]
I think to fix this, we'd want to change the beginning of `Cleaner.clean` and `Linker.link` to check if the input is a `six.text_type` and if not, raise a `TypeError` with an appropriate message.

I'm not going to work on this, but I'd accept a PR.

**Comment by willkg** [comment]
@ivellios @overfl0 Either of you interested in working on this?

**Comment by ivellios** [comment]
@willkg I will do. But... shouldn't it be rather `six.string_types` instead? I know it's time to move to Python 3.x, but with `text_type` it will not work for ASCII strings in Python 2.4+

**Comment by ivellios** [comment]
Oh, and should I follow the release process: https://bleach.readthedocs.io/en/latest/dev.html#release-process ? Or just push changes with tests passing and let you handle the versioning, contributions and so on?

**Comment by willkg** [comment]
@ivellios My bad--you're right. It should check for `six.string_types`.

Regarding the release process, that's only something I do--not you. If you want to fix this, just submit a PR covering the code change and tests and I can handle it from there.

Thank you!

**Comment by willkg** [comment]
This is fixed now. Closing it out.
