### ISSUE TITLE
Bleach 2.0 adds &lt;tbody&gt; tags as plaintext to the table after bleach.clean is run

### ISSUE THREAD

**Issue by t4ec** [mozilla/bleach#295]
Just an example of what bleach 2.0 produces when we clean table:

```
In [5]: bleach.clean('<table><tr><td>hi</td></tr></table>', ['table','td','tr'])
Out[5]: '<table>&lt;tbody&gt;<tr><td>hi</td></tr>&lt;/tbody&gt;</table>'
```

As a result HTML page shows two ```tbody``` tags as plaintext, which breaks the table view and feel.

Bleach 1.5 does not have this issue.

**Comment by willkg** [comment]
I'm not sure why html5lib is adding `tbody`. `tr` is a valid child of `table`, so it doesn't need to.

As a work around, you can probably add `tbody` to the list of allowed tags.

**Comment by willkg** [comment]
I'm not going to change the behavior here. Sorry!
