### ISSUE TITLE
option to collapse fully-sanitized lines when cleaning

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#297]
(this is an idea brought up for discussion)

Bleach sanitizes content in-place, which is the ideal behavior for most situations, allowing a "line for line" comparison of input and output.

In certain situations, it may be desirable to omit those lines which become "empty" because of sanitization

    >>> line = "one\ntwo\n\nthree\n\nfour"
    >>> bleach.clean(line)
    u'one\ntwo\n\nthree\n\nfour'

In the case above, a user might want the output to not include the `\n\n` between "two" and "three" as it was caused by a stripped node occurring both after & before a newline.

    u'one\ntwo\nthree\n\nfour'

**Comment by willkg** [comment]
Thanks for writing this up!

I'm not sure I see how this fits in the goals of the Bleach project. https://bleach.readthedocs.io/en/latest/goals.html

Does having multiple blank lines create unsafe HTML scenarios?

**Comment by willkg** [comment]
I'm going to close this out. I think this could be covered by #234 maybe, but it's outside the scope of `bleach.clean`.

**Comment by EmilStenstrom** [comment]
@willkg: I’m not sure how removing the contents of style and script tags (unsafe code), relates to handling white space?

**Comment by jvanasco** [comment]
@EmilStenstrom  I think it's because he envisions a 'prettify' command would handle the style/css, and that new command would ostensibly be able to handle the whitespace and other 'non-secure' concerns because it would be invoked in the same hooks as stripping the style and script tags.

I had tried strip the content of the style and script tags in a fork of bleach for a PR, but couldn't make much progress. it seemed like the tags are removed/escaped during parsing and tokenization, not during rendering/serialization - which is why things like the filtering system can't be used to handle these concerns.
