### ISSUE TITLE
Cleaning comments in style-tags

### ISSUE THREAD

**Issue by rickardlindberg** [mozilla/bleach#304]
In the following snippet, I expected the comment in the style tag to be removed as well, but it is not. Is this expected behavior? How can I also get rid of the comments inside style tags?
```
>>> html = "foo <strong>a <!-- what --> b</strong> <style type='text/css'>a <!-- what --> b</style> bar"
>>> bleach.clean(html, tags=["strong", "style"], strip_comments=True)
'foo <strong>a  b</strong> <style>a <!-- what --> b</style> bar'
```

**Comment by willkg** [comment]
Hi! Thank you for reporting this!

I spent a few moments looking into it. I think there are a couple of things here.

First, `<!-- ... -->` isn't a valid CSS comment, so it's being interpreted as data.

https://developer.mozilla.org/en-US/docs/Web/CSS/Comments

Second, if you change your example to use a valid CSS comment:

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> bleach.clean('<style>/* foo */</style>', tags=['style'], strip_comments=True)
'<style>/* foo */</style>'
>>> 
```

it still keeps the comment. That's because `strip_comments` only strips out HTML comments.

https://bleach.readthedocs.io/en/latest/clean.html#stripping-comments-strip-comments

I'm not sure whether Bleach should strip CSS comments as well.

What're you trying to do? What's the use case for keeping `style` tags, but stripping CSS comments?

**Comment by rickardlindberg** [comment]
Thanks for your reply.

What I'm trying to do is remove the style tag altogether. (The above example was from an experiment with two passes of bleach: first to clean the inside (remove the comment) and then to remove the style tag altogether.)

Here is a better example of what I'm trying to do:

```
>>> html = "foo <style><!-- some css --></style> bar"
>>> bleach.clean(html, tags=[], strip="true", strip_comments=True)
'foo &lt;!-- some css --&gt; bar'
```

I would have expected bleach to strip out the the contents of the style tag as well (since it looks like an html-comment), leaving only `foo  bar` in the example above.

I have read the source code a bit more for html5lib and my current thought is that the content of the style tag is not interpreted as a comment, but just as a text blob.

**Comment by willkg** [comment]
I think this is covered in issue #185. That and a few other issues were generalized into #234. I'm going to close this issue in favor of that one. You can add comments there if you like.

In the meantime, one thing you could do is to not strip the style tags in `bleach.clean` directly, but remove the `style` tag and everything it contained in a filter that runs after the sanitizer filter.

There's some details on filters here:

https://bleach.readthedocs.io/en/latest/clean.html#html5lib-filters-filters

If you need help with that, let me know, but it'll probably take me a week or so to find the time to write it up.

Hope that helps!

**Comment by rickardlindberg** [comment]
Thanks. I ended up with this for now:

```python
def _sanitize_html(html):
    class StripFilter(Filter):
        def __iter__(self):
            open_tags = []
            for token in Filter.__iter__(self):
                if token["type"] in ["EmptyTag", "StartTag"]:
                    open_tags.append(token["name"])
                if not set(STRIP_TAGS_COMPLETELY).intersection(set(open_tags)):
                    yield token
                if token["type"] in ["EmptyTag", "EndTag"]:
                    open_tags.pop()
    KEEP_TAGS_ATTRIBUTES = {
        "p": [],
        "div": [],
        "br": [],
        "i": [],
        "em": [],
        "b": [],
        "strong": [],
        "blockquote": [],
    }
    STRIP_TAGS_COMPLETELY = [
        "style",
        "script",
    ]
    return bleach.sanitizer.Cleaner(
        tags=list(KEEP_TAGS_ATTRIBUTES.keys())+STRIP_TAGS_COMPLETELY,
        attributes=KEEP_TAGS_ATTRIBUTES,
        strip=True,
        strip_comments=True,
        filters=[StripFilter]
    ).clean(html)
```
