### ISSUE TITLE
Linkify creates http link in mail addresses when host contains a hyphen

### ISSUE THREAD

**Issue by sedrubal** [mozilla/bleach#322]
Linkify recognizes part of mail addresses with an hyphen (`-`) in the host part as link, (even) if `parse_email=False`:

```python
>>> linkify('foo@bar-baz.com')
'foo@bar<a href="http://-baz.com" rel="nofollow">-baz.com</a>'
```

One outcome of this is #300 which was fixed with #302.

**Comment by g-k** [comment]
Closing as a duplicate of #60
