### ISSUE TITLE
UnicodeDecodeError on setup

### ISSUE THREAD

**Issue by EP01** [mozilla/bleach#324]
I'm seeing the following error when trying to compile version 2.1 of `bleach`.

``` 
python3 setup.py build -b __py3_build
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    long_description=get_long_desc(),
  File "setup.py", line 30, in get_long_desc
    desc += open('CHANGES').read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1236: ordinal not in range(128)
```

**Comment by willkg** [comment]
It's probably related to this since that adds a non-ASCII character to the CHANGES file:

https://github.com/mozilla/bleach/commit/f904b5214d2fe84ed3332cb50171c77c4b68290c

Seems like you're running some version of Python 3.5. I'm not able to reproduce it with 3.4.5, 3.5.3. or 3.6.0. I don't have other versions on this system.

What context are you running that command in?

**Comment by EP01** [comment]
Thanks for your response. I'm running Python 3.5.4 on Solus. I'm building in a chroot environment ([solbuild](https://github.com/solus-project/solbuild)) in order to package the update for distribution. I can try to do some further investigation after work, perhaps removing the non-ASCII character from the CHANGES file to see if that works.

**Comment by willkg** [comment]
It's probably from a missing `LANG` or whatever it is that keys Python into the default encoding to use for opening files.

I'll fix this and roll a Bleach 2.1.1 next week.

**Comment by willkg** [comment]
I fixed it, added a test for it so it's unlikely to happen again, and pushed out v2.1.1 just now.

Let me know if you hit any other issues!

**Comment by EP01** [comment]
Thanks very much for the quick fix, working fine now!
