### ISSUE TITLE
run bleach tests on windows in CI

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#331]
Bleach currently uses Travis CI which covers tests on *nix systems "good enough". However, Windows is pretty different in a bunch of ways.

This issue covers setting up Bleach with AppVeyor as well.

**Comment by g-k** [comment]
GH actions are another option now: https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by hugovk** [comment]
Please see PR #514 to test on Windows, Linux and macOS on GitHub Actions.
