### ISSUE TITLE
Cleaner.clean raises TypeError if text=None

### ISSUE THREAD

**Issue by j-i-l** [mozilla/bleach#334]
https://github.com/mozilla/bleach/blob/19dd5ba885e5429cef63a4531675a73ca668edcc/bleach/sanitizer.py#L186-L203

This can happen when running migration in Django (1.11) in Python 2.7 using the [html_sanitizer](https://github.com/ui/django-html_sanitizer) app. The model field in question is [SanitizedTextField](https://github.com/ui/django-html_sanitizer/blob/master/sanitizer/models.py#L32) although I doubt this is of importance here.

Not sure if this is the desired behavior, if not the `if not text:` clause from L201 could simply be moved above the instance check.

**Comment by willkg** [comment]
We changed it so that it requires a string type, so passing in `None` isn't going to fly. I suggest wrapping the `bleach.clean` call with a check for when `text=None`.

This is listed as a backwards-incompatible change for version 2.1.

Hope that helps! Sorry it bit you!

**Comment by j-i-l** [comment]
That helps indeed! Thanks for getting me up to speed and sorry for bothering. I should have had a look at the changelogs first. :slightly_frowning_face:

**Comment by willkg** [comment]
No worries at all! Happy to help!
