### ISSUE TITLE
Add upper limit to html5lib dependency

### ISSUE THREAD

**Issue by timster** [mozilla/bleach#339]
As you probably know, html5lib updating their version to 1.0.1 caused a problem for anyone trying to install bleach 2.1.1. This was solved quickly (thank you!) by releasing 2.1.2 with changes to support html5lib 1.0.1.

With something like this in `install_requires`, bleach 2.1.1 would have continuted to work.

`html5lib>=0.99999999pre,<1`

WIth the current dependency requirement, future releases of html5lib can break current versions of bleach.

Would you consider adding an upper limit to the dependency going forward? Might be a little easier now that html5lib is on semver. Maybe something like this:

`html5lib>=1.0.1,<1.1`

**Comment by willkg** [comment]
In this case, html5lib had 1 release in the last 1.5 years which essentially I drove. It's not a highly active project. In fact, I wrote the patch that broke Bleach, so I knew what I needed to fix. I pushed out a release 2 hours later.

In this case, I don't think it makes sense to add an upper bound which *forces* us to do a release every time html5lib does a release.

Thank you for thinking about it!

**Comment by timster** [comment]
Makes sense. Thanks!

**Comment by sliwinski-milosz** [comment]
In my opinion upper limit should be added as suggested.

Thanks to that we will be sure that same issue won't happen again. I prefer to install newer version of dependency once integration testing is done rather than automatically. Especially that it was known that new release of html5libwill come and issue has not been avoided.

**Comment by willkg** [comment]
Hi! I appreciate you have an opinion on this and it's definitely different from mine. For the reasons I stated above, I'm not planning to do this in Bleach. I suggest you look into dependency pinning which pip and other tools support. I'm sorry this will disappoint you, but hope that maybe pinning will help!

**Comment by timster** [comment]
What do you suggest for version pinning in this case?

We were pinned to `bleach==2.1.1` but fresh installs of 2.1.1 no longer work due to incompatability with the latest html5lib.

`bleach==2.1.2` only works until an incompatible version of html5lib is released.

**Comment by sliwinski-milosz** [comment]
Both approaches have their pros and cons.

AFAIK Html5lib has started to use symantic versioning. As they increased major version of their package -> they introduced backward compatibility breaking change. I might be wrong but adding pinning for major version changes is reasonable here.

The good argument for keeping the current approach is if we consider bleach as a security related package. So in case that using the older version could lead to security issues, then it is good to fail whenever latest version is not installed.

@timster we can still pin the version of html5lib in our apps requirements files. That should fix older versions of bleach:
`html5lib==1.0b10`
