### ISSUE TITLE
ImportError: cannot import name ReparseException

### ISSUE THREAD

**Issue by DudkinON** [mozilla/bleach#340]
I tried to run the flask app with docker-compose. When I run docker container, I get following error:
```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from bleach import clean
  File "/usr/local/lib/python2.7/dist-packages/bleach/__init__.py", line 11, in <module>
    from bleach.sanitizer import (
  File "/usr/local/lib/python2.7/dist-packages/bleach/sanitizer.py", line 10, in <module>
    from html5lib.constants import (
ImportError: cannot import name ReparseException
```
Can someone help me solve this issue? Thanks in advance.

**Comment by willkg** [comment]
Hi! What happened is that there was a html5lib-python 1.0 release and the version of Bleach you're using doesn't support that. You can do one of two things:

1. upgrade Bleach to 2.1.2 which does support html5lib-python 1.0
2. pin html5lib-python to a version that works with whatever version of Bleach you're using

Hope that helps!
