### ISSUE TITLE
sources download link in pypi broken

### ISSUE THREAD

**Issue by scphantm** [mozilla/bleach#344]
on pypi, the sources download for 2.1.2 is busted.  This is causing big problems for me.  the link on the pypi site is 

https://pypi.python.org/packages/b3/5f/0da670d30d3ffbc57cc97fa82947f81bbe3eab8d441e2d42e661f215baf2/bleach-2.1.2.tar.gz#md5=d0b14ae43a437ee0c650e04c6063eedd

when you try to click that on a browser, i get a network error.  The wheel downloads fine, but i need the sources fixed.

**Comment by willkg** [comment]
What network error are you getting?

**Comment by scphantm** [comment]
connection reset.  im trying on a machine outside our network and the link works fine outside.  Its just weird that i run my script to download thousands of libraries from pypi for our internal pypi refresh and all of a sudden this ONE library stops working.  you don't do anything odd like publish it on some other site with some kind of weird rerouting do you?  i know our firewall blocks certain types of reroutes.

**Comment by willkg** [comment]
I'm not doing anything. It's just like all the other libraries I maintain and push to PyPI. I have no explanation for why this would be failing for you. I suggest bringing it up with the PyPI volunteer infra team. Maybe opening a support ticket here?: https://sourceforge.net/p/pypi/support-requests/

**Comment by scphantm** [comment]
ugh.  ok, thanks.  ill call my firewall team.  maybe our in-stream virus scanner thinks this is a virus or something.  thats just typically a different error.
