### ISSUE TITLE
allow sanitization of attributes based on attribute value

### ISSUE THREAD

**Issue by inducer** [mozilla/bleach#348]
I'm following up from #346 (closed), which covered my need of letting some (but not all) `data:` URLs in `src` attributes pass the sanitizer. What that PR did was piggyback on attribute filters to determine when a value should be allowed to bypass [this logc](https://github.com/mozilla/bleach/blob/8706b5373b633407e804b1b2975edf8760067ff7/bleach/sanitizer.py#L511-L549) that is otherwise unconditionally applied.

In that PR, @willkg said:

> I suspect you can achieve what you're trying to achieve without making a substantial behavior change to Bleach.

Unless `data:` is added to the `allowed_protocols` (which seems risky), I don't see how this could be accomplished, but I would be happy to be educated.

**Comment by willkg** [comment]
You're not providing many details, so I'm going to infer what I can. If any of this is incorrect, please let me know.

Seems like you're trying to sanitize text and in that text it's possible to have HTML tags that have an attribute with a value that has a `data:` protocol. There are some URLs with the `data:` protocol that are ok, but the rest you want to disallow.

Does that sound right?

If so, I think you could allow `data:` as a protocol and for the attributes that allow protocols, set up a callbable that checks the value for data protocols and allows/denies it there. That should be pretty straight-forward.

Does something like that work?

**Comment by inducer** [comment]
> Does that sound right?\

Yep.

> Does something like that work?

I agree that it works in theory. I'm not exceedingly happy with it, because if I am to assume that `data:` URLs are dangerous in some way, I can now no longer rely on bleach on catching those URLs. In particular, I'd have to catch all possible usage sites of those URLs (`script.src`? `style.link`? `a.href`?...) with validation callbacks. That seems inherently dangerous, because I'm bound to miss something. In that sense, I find that it inspires considerably less confidence.

**Comment by inducer** [comment]
Fair enough. Thanks for your help.

**Comment by dzhuang** [comment]
@willkg A question, is there any way for  `bleach.clean` to remove unwanted attributes if a tag, which is not in `bleach.ALLOWED_TAGS` and was not specified in `tags` arg in `clean`, contains those attribute? Thanks.

**Comment by dzhuang** [comment]
For example, 
`<a href="data:,Evilcss"></a>` is cleaned to `<a></a>` .

While `<style src="data:,Evilcss">` is cleaned to `&lt;style src="data:,Evilcss"&gt;&lt;/style&gt;`, instead of `&lt;style &gt;&lt;/style&gt;` . ( `style` is not in `bleach.ALLOWED_TAGS`）.

**Comment by willkg** [comment]
No, I don't think there's a way to do that without subclassing `BleachSanitizerFilter` and overriding `disallow_token`.

**Comment by dzhuang** [comment]
@willkg thanks. Then I'd rather `strip` it.
