### ISSUE TITLE
Linkify with html5lib 1.0.1 not working?

### ISSUE THREAD

**Issue by ntucker** [mozilla/bleach#349]
Starting with my code that calls linkify:
```
  File "logos/discussion/tasks.py", line 140, in create_youtube_topic
    paragraphs = bleach.linkify(html.escape(description), callbacks=[external_site]).split('\n\n')
  File "bleach/__init__.py", line 146, in linkify
    return linker.linkify(text)
  File "bleach/linkifier.py", line 157, in linkify
    return self.serializer.render(filtered)
  File "html5lib/serializer.py", line 398, in render
    return "".join(list(self.serialize(treewalker)))
  File "html5lib/serializer.py", line 301, in serialize
    for (_, attr_name), attr_value in token["data"].items():
```

It seems like html5lib is expecting something a bit different. Not sure exactly what was going on here, but I have
```
bleach==2.1.2
html5lib==1.0.1
```

in my pip requirements.

Didn't trace the values all the way through manually so if I'm using this wrong, guidance would be appreciated. (html.escape is from django and should return a string, so it seems odd that my line would be the issue)

**Comment by willkg** [comment]
Can you add some sample code that would trigger this failure?

**Comment by willkg** [comment]
I haven't heard from the original reporter in a while and I can't reproduce this, so I'm going to close it out.

If someone can reproduce it, please include steps to reproduce or sample code or something like that.
