### ISSUE TITLE
Support data URIs

### ISSUE THREAD

**Issue by iurisilvio** [mozilla/bleach#351]
My HTML has some images with data URIs (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

I can just add `'data'` to `allowed_protocols`, but `html5lib` handle it whitelisting data URI content types too. It is better than allowing any content type.

I wrote PR #350 for that, copying how html5lib filter works.

https://github.com/html5lib/html5lib-python/blob/f7708c43f86c6e912dd29f3d77bd17bc76695d51/html5lib/filters/sanitizer.py#L825

**Comment by willkg** [comment]
Can you talk more about why your HTML has data URIs with images? Where's it coming from? Are users writing it by hand?

**Comment by willkg** [comment]
@iurisilvio Can you talk more about why your HTML has data URIs with images? Where is the data coming from? Are users writing it by hand?

**Comment by willkg** [comment]
After you wrote up this issue, I changed some parts of the sanitizer so it's easier to override uri sanitizing. That's in 73dfef1d.

Does that make it easier to do what you want to do without adding `ALLOWED_CONTENT_TYPES` and all that? I think you could do something like:

```
class MySanitizer(BleachSanitizerFilter):
    def sanitize_uri_value(self, value, allowed_protocols):
        parsed = urlparse(value)
        if parsed.scheme == 'data':
            # do your thing here
        else:
            return super(MySanitizer, self).sanitize_uri_value(value, allowed_protocols)
```

**Comment by iurisilvio** [comment]
Great! It works for me! Thanks!

**Comment by willkg** [comment]
I'm glad that worked out! I'm really sorry it took so long to get back to you. Thank you for writing this up!
