### ISSUE TITLE
clean drops attribute namespaces

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#362]
From https://github.com/mozilla/bleach/pull/361#pullrequestreview-105159247

This works fine:

```
allowed_attrs['svg'] = ['xmlns', 'xlink']

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">alert</svg>
--
<svg xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">alert</svg>
```

This drops the namespace:

```
allowed_attrs['svg'] = ['xmlns', 'xmlns:xlink']

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">alert</svg>
--
<svg xmlns="http://www.w3.org/2000/svg">alert</svg>
```

This should work correctly in Bleach `clean`.

**Comment by willkg** [comment]
The underlying issue is in html5lib's serializer and covered here:

https://github.com/html5lib/html5lib-python/issues/59

Maybe we can fix it in html5lib? Maybe we should roll our own serializer?

In either case, I think this is an edge use case and not something I'm going to tackle until someone has a compelling reason to.

**Comment by casiec** [comment]
Hey, would it be possible to release this soon? It is causing some problems for me.

**Comment by willkg** [comment]
@casiec Are you asking if it's possible to release a new version of Bleach with this issue fixed? If so, this issue hasn't been fixed, yet.

**Comment by willkg** [comment]
I'm not working on this at present.

If you or someone else wants to tackle it, the details in https://github.com/mozilla/bleach/issues/362#issuecomment-374602450 should help.

If not, then there's no ETA.

**Comment by casiec** [comment]
Thanks for the info!

**Comment by aadithpm** [comment]
Hey, is this still open? Can I try taking a shot at fixing it?

**Comment by willkg** [comment]
@aadithpm Sure! Let me know if you have problems, but I'm pretty sure everything I know is in the comments.

**Comment by aadithpm** [comment]
Yep, there is a lot of info in the comments.

Do you want me to look at solving this as an edge use-case? I think the other suggestion(s) is/are way past the scope of what I know, haha.

**Comment by willkg** [comment]
I'm not going to fix this. Sorry!
