### ISSUE TITLE
"&quot;" in styles should be considered as a valid value

### ISSUE THREAD

**Issue by lig** [mozilla/bleach#363]
bleach 2.1.3

Style value like this `font-family: &quot;Droid Sans&quot;` is being treated as invalid.

However, this works in most browsers and is, in fact, a common practice.

**Comment by willkg** [comment]
How did this come up? What is your use case?

**Comment by lig** [comment]
@willkg I have an external html data which I'm sanitizing using bleach. I would like to allow a css attribute. This attribute is one of a long `style` definition. And because of `font-family` contains those `&quot;` attributes, Bleach drops the entire style definition including the attribute I would like to allow.

**Example html**
```html
<span style="font-family: &quot;Droid Sans&quot;; white-space: pre-wrap;">Some text</span>
```

In this case, Bleach will drop the entire style attribute value after failing to match to the gauntlet regex regardless of the `Cleaner.styles` value.

I expect that with `Cleaner(tags=['span'], attributes={'span': ['style']}, styles=['white-space'])` it should produce the following output

```html
<span style="white-space: pre-wrap;">Some text</span>
```

**Comment by willkg** [comment]
Can you check to see if tinycss or tinycss2 can parse that style?

* https://pypi.python.org/pypi/tinycss
* https://pypi.python.org/pypi/tinycss2

I ask because we have issue #248 that covers rewriting that bit using a library. Maybe that fixes this issue, too?

**Comment by lig** [comment]
```
In [19]: s = 'font-family: "Droid Sans"; white-space: pre-wrap;'
In [24]: tinycss2.parse_declaration_list(s)
Out[24]: [<Declaration font-family: …>, <WhitespaceToken>, <Declaration white-space: …>]
In [25]: s = 'font-family: &quot;Droid Sans&quot;; white-space: pre-wrap;'
In [26]: tinycss2.parse_declaration_list(s)
Out[26]:
[<Declaration font-family: …>,
 <ParseError invalid>,
 <WhitespaceToken>,
 <Declaration white-space: …>]
In [33]: tinycss2.parse_declaration_list(s)[0].serialize()
Out[33]: 'font-family: &quot'
In [34]: tinycss2.parse_declaration_list(s)[1].message
Out[34]: "Expected ':' after declaration name, got ident."
```

Conclusion: tinycss2 is no help here.

**Comment by lig** [comment]
Looks like this is enough before the rest of the routine

```
In [40]: import html
In [41]: html.unescape('font-family: &quot;Droid Sans&quot;; white-space: pre-wrap;')
Out[41]: 'font-family: "Droid Sans"; white-space: pre-wrap;'
```

**Comment by willkg** [comment]
Ahh... interesting. Mmm... I just fixed a related issue this week. I think I can fix this one the same way. I'll try to do that this week.

Thank you so much for spending the time to flesh this out!
