### ISSUE TITLE
Just test if string is a valid URL

### ISSUE THREAD

**Issue by josephernest** [mozilla/bleach#366]
Is it possible to use `bleach` to just test if a string is a valid URL? (and not linkify anything but just check)

Example:

    bleach.isvalidurl('helloworld') #False
    bleach.isvalidurl('http://helloworld.com/blah?id=127') #True
    bleach.isvalidurl('www.helloworld.com') #False
    bleach.isvalidurl('www.helloworld.com', permissive=True ) #True

PS: I already use `bleach` for sanitizing/cleaning

It would give a definitive answer to this problem: https://stackoverflow.com/q/7160737/1422096 which doesn't really have a good answer (tested, maintained, etc.). (Currently it only has half-working recipes.)

**Comment by willkg** [comment]
URL validation is outside the scope of Bleach.

Bleach sanitizes HTML attribute values that contain URIs using this code:

https://github.com/mozilla/bleach/blob/b5ad8572b790df453fb844859c7b22d24bd974fd/bleach/sanitizer.py#L581

And linkifies url-ish things with this code:

https://github.com/mozilla/bleach/blob/b5ad8572b790df453fb844859c7b22d24bd974fd/bleach/linkifier.py#L60

If you want to use one of those, that's cool, but it's not a supported use of Bleach and liable to change at any time and it's likely to hedge towards "this substring of this larger string is probably a URL" and not towards "this string is a valid URL".

Sorry this isn't more helpful!
