### ISSUE TITLE
TLD 'fit' is not recognized

### ISSUE THREAD

**Issue by M1hacka** [mozilla/bleach#367]
Hi, url 'http://starproject.fit' is not recognized as link, as 'fit' is not in TLDS list.

**Comment by M1hacka** [comment]
As well as localized domain names like `https://xn--80aaksdi3bpu.xn--p1ai/`

**Comment by willkg** [comment]
This is essentially what's covered in issue #223. There are lots and lots of TLDs that are not recognized. Maintaining that is overly burdensome, so I opted not to do it.

You can change the `TLDS` list and regenerate the `URL_RE` using it and then get whatever top level domains you want.

Something like this:

```
from bleach import linkifier

my_list_of_tlds = [...]
linkifier.URL_RE = linkifier.build_url_re(tlds=my_list_of_tlds)
```

and then linkify will use that.

The localized domains issue is a separate issue. Can you open up a new issue for that, please?

Hope that helps!
