### ISSUE TITLE
Localized TLDs are not parsed by linkify.

### ISSUE THREAD

**Issue by M1hacka** [mozilla/bleach#368]
Localized domains like `https://xn--80aaksdi3bpu.xn--p1ai/` are not parsed by linkify. Related issue: https://github.com/mozilla/bleach/issues/367

**Comment by M1hacka** [comment]
1) This domain is correct link `https://дайтрафик.рф`. All of it. As you see, `--p1ai/` is out of tag, so, bleach worked incorrectly.
2) What would be best - if bleach finds `https://дайтрафик.рф` in text an transforms it to `'<a href="https://xn--80aaksdi3bpu.xn--p1ai/" rel="nofollow">https://дайтрафик.рф</a>'` or `'<a href="https://дайтрафик.рф" rel="nofollow">https://дайтрафик.рф</a>'`

**Comment by willkg** [comment]
This is way outside my knowledge area, so this isn't something I'm going to be able to work on any time soon.

If you want to tackle it, please do! Otherwise, this is going to wait for someone else to help out on.

Sorry about that!

**Comment by is2ei** [comment]
@willkg Thanks for your reply!  
Japan also has localized domain e.g. `http://日本語.jp` . This is first time for me to implement punycode converter, though.

**Comment by jvanasco** [comment]
@is2ei  if you are still working on this, `tldextract` may have some code you can use https://github.com/john-kurkowski/tldextract

**Comment by g-k** [comment]
Closing, since the TLD list is configurable now (refs: #223).
