### ISSUE TITLE
Upgrade Twine?

### ISSUE THREAD

**Issue by brainwane** [mozilla/bleach#371]
Hi! I'm a [Twine](https://twine.readthedocs.io) maintainer; thanks for using Twine. I noticed you've pinned an old version of Twine in [your requirements file](https://github.com/mozilla/bleach/blob/master/requirements.txt#L13). Twine [has changes in 1.11.0](https://twine.readthedocs.io/en/latest/changelog.html) that you might find useful, and I hope you'll upgrade. If you have any trouble upgrading, please do [let us know](https://github.com/pypa/twine/issues).

**Comment by willkg** [comment]
I'm not sure why we pinned twine at all. That's intriguing.

I'll update that now. Thank you for bringing it up!

**Comment by brainwane** [comment]
Thanks! I got [your libraries.io page](https://libraries.io/github/mozilla/bleach) to re-sync so it'll reflect the update.
