### ISSUE TITLE
LinkifyFilter not working for URLs with ampersands

### ISSUE THREAD

**Issue by Alex3917** [mozilla/bleach#374]
Example with bleach 2.1.3:

```
from bleach import Cleaner
from bleach.linkifier import LinkifyFilter

url1 = 'http://a.co?b=1&c=2'
url2 = 'http://a.co?b=1&amp;c=2'

cleaner = Cleaner(filters=[LinkifyFilter])
cleaner.clean(url1)
cleaner.clean(url2)
```

Both result in `<a href="http://a.co?b=1">http://a.co?b=1</a>&amp;c=2`

**Comment by willkg** [comment]
I don't generally spend time on the linkify stuff. If you or someone else wanted to tackle this, then that'd be great!

**Comment by Alex3917** [comment]
I'll look into it, can't guarantee I'll be able to figure it out though.

Also, FWIW it seems to be the same situation for URLs with # characters (fragments). It seems like the regex isn't the issue because linkifying works when just running `bleach.linkify`.

**Comment by Alex3917** [comment]
I still haven't solved this, it seems to be related to the tokenization process though. There is a similar issue for plaintext emails, where there can be newline characters should be (but are not) allowed before or after a dash, except for at the end of the URL. E.g.:

SIMPLE_URL_REGEX = `'(http[s]?://(?:(?:-\n|\n-)?[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)'`

**Comment by willkg** [comment]
Maybe `LinkifyFilter` needs to join consecutive `Characters` tokens and then do its thing?
