### ISSUE TITLE
bleach.sanitizer.ALLOWED_TAGS_EXTENDED

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [mozilla/bleach#380]
I open this feature request after a discussion on IRC in #bleach.

`FEATURE REQUEST` Add a `bleach.sanitizer.ALLOWED_TAGS_EXTENDED` list to bleach. This list should be an extension of `bleach.sanitizer.ALLOWED_TAGS` and should contain more tags that are considered safe but are not an "extremely minimal set of tags" as described [in this issue](https://github.com/mozilla/bleach/issues/174#issuecomment-153032248).

**Comment by willkg** [comment]
Hi! This is something that comes up from time-to-time and while I understand the crux of the issue, I really don't want to do this.

Bleach is a security-focused library. The problem domain is HUGE. It's really important to keep the complexity as minimal as possible so as to ease the maintenance burden and also to prevent security issues.

Not accepting this shouldn't block you or anyone else from doing things you need to do. Bleach is flexible and you can use your own allowed-tags list. I don't think this is a must-have feature.

If you want to start a project with a list of non-minimal tags that you assert are safe, that'd be cool. Maybe there are like-minded people who would work with you on that.

Hope that helps!

**Comment by DylanYoung** [comment]
@willkg  I think your decision here is reasonable, but I'll admit I'm super curious from a security perspective: what was the reason for choosing the minimal set of tags that you did?  Is this documented anywhere?
