### ISSUE TITLE
bleach.clean() fails to decode some special characters

### ISSUE THREAD

**Issue by rudiad** [mozilla/bleach#384]
**Premise**
I am not 100% sure how the clean method does its stuff (haven't sifted through the source code yet). However, it seems like it likely encodes the string, strips the offending tags / attributes, then decodes the string back for the final result.

**Issue**
This seems to not be operating correctly for certain special characters.

Input ```bleach.clean('!@#$%^&*()_+}{:"<>?,./;'[]1234-=\|`~');```

Output `!@#$%^&amp;*()_+}{:"$lt;&gt;>?,./;'[]1234-=\|`~`

That is a bit of a jumble of characters but you can see that `&` `<` and `>` are now represented by their HTML encoded entities. When using `bleach.clean()` I now end up having to do a follow up step of replacing those entities with their actual character if I am using the result for anything other than HTML parsing.

**Comment by willkg** [comment]
I don't know what you mean by "using the result for anything other than HTML parsing" since Bleach doesn't return an AST or other parser output.

Bleach's main purpose is to sanitize user-provided input for safe us in an HTML context:

https://bleach.readthedocs.io/en/latest/goals.html#main-goal-is-to-sanitize-input-of-malicious-content

Does that sound like what you're trying to use it for? If not, what are you trying to use it for?

**Comment by rudiad** [comment]
I was using it to clean potential security threats from form inputs. Removing unwanted style and script tags from text inputs. I know this isn't its intended use, but it seems to handle decoding all of the other special characters just fine so I figured it was worth calling out the issue.

A potential use case would be taking HTML from the current page, cleaning it, converting it to JSON and cleaning it then passing it to some sort of API or service that might render the html and return it somewhere else.

**Comment by willkg** [comment]
Bleach is doing the right thing here. The characters you pointed out are being escaped which is one of the key parts of sanitizing.

I don't understand the use case you're suggesting. Maybe you don't really need sanitized text at all?

I don't think there's anything I want to do here, so I'm going to close it out.

Thank you for writing it up!
