### ISSUE TITLE
improve bleach documentation

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#397]
I think the documentation feels dense and it lacks good flow. I'm pretty sure a lot of the language could be simplified and reduced to be clearer and more direct.

This issue covers expounding specific issues and then either fixing them or spinning off new issues.

**Comment by Shivansh2407** [comment]
Can I help you on this issue

**Comment by willkg** [comment]
@remote007 What do you mean by MR?

**Comment by remote007** [comment]
Merge Requests . i.e, is it available to work on ?

**Comment by willkg** [comment]
@remote007 I think this issue is lacking definition, so until it's more clearly defined (e.g. what exactly should be done?), it's not a good issue to work on.

**Comment by willkg** [comment]
I'm not going to work on this.
