### ISSUE TITLE
abbr is escaped when using linkify

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#400]
From IRC:

```
willkg: I'm doing the work to upgrade AMO to bleach3.0 but I may have found a
regression with the linkify fix (?).
`bleach.linkify('<abbr title="laugh out loud">lol</abbr>', skip_tags=['abbr'])` escapes
the `<abbr>` tag.  Is there a way to have linkify _not_ do that?
```

Looks like `abbr` isn't in `HTML_TAGS`. We should add it.

**Comment by Deimos** [comment]
I was just testing bleach 3.0 and there seems to be more than this missing - so far from my tests I've also noticed bleach is now escaping `del`, `ins`, `sub`, `sup`, and `span` tags.

**Comment by willkg** [comment]
@Deimos Can you do a PR for that?

**Comment by Deimos** [comment]
@willkg sure, I can. Is it indicating a larger issue though, since it seems like some significant tags aren't currently covered? Should I look for a more comprehensive list of HTML5 tags somewhere, instead of building off these html5lib constants, since they're obviously pretty incomplete?

**Comment by willkg** [comment]
Two things:

1. You should write up a new issue to cover the new work. This issue was specifically about the abbr tag.
2. I don't have any preferences on how you want to solve this.

Hope that helps!
