### ISSUE TITLE
v3.0.2 tag missing on GitHub

### ISSUE THREAD

**Issue by hairmare** [mozilla/bleach#418]
`3.0.2` is already available on PyPi: https://pypi.org/project/bleach/3.0.2/

But missing from the [GitHub Releases](https://github.com/mozilla/bleach/releases): https://github.com/mozilla/bleach/releases/tag/v3.0.2

It looks like it just needs to be Released on GitHub as well.

**Comment by willkg** [comment]
Oops--I missed a step in my release process. The tag is pushed now. Sorry about that!

**Comment by hairmare** [comment]
Thanks!
