### ISSUE TITLE
Linkify 3.0 messing up my tags

### ISSUE THREAD

**Issue by Koopiq** [mozilla/bleach#420]
```python
bleach.linkify('<span>  https://example.com  </span>')
```
in >=3.0 yields
```html
&lt;span&gt;  <a href="https://example.com" >https://example.com</a>  &lt;/span&gt;
```
Whilte in 2.1.4 it was
```html
<span>  <a href="https://example.com">https://example.com</a>  </span>
```

I don't need any help from `linkify` with sanitizing my data because I've already sanitized what I need and the rest I need to have unsanitized. All I need from `linkify` is to **linkify** anything that looks like url and to not mess with the rest.

Is there any way to revert back to the old behavior please?

**Comment by willkg** [comment]
Pretty sure this is what #409 covers and it'll get fixed in a release after we land #412.

Hopefully, I can get to that soon. Sorry about that!
