### ISSUE TITLE
Type stubs for bleach

### ISSUE THREAD

**Issue by srittau** [mozilla/bleach#424]
For my own use, I have written type stubs for bleach: https://github.com/srittau/python-stubs/tree/master/stubs/bleach. With your permission I would like to include them in [typeshed](https://github.com/python/typeshed) so they get included in future releases of type checkers like mypy.

The stubs are mostly complete, just the two html5lib filter classes are incomplete, partly because html5lib does not have type stubs, yet.

**Comment by willkg** [comment]
That sounds fine as long as it doesn't add work or additional obligations for me. If it does add work or obligations for me, then I'd like to understand what that work is before I commit to anything.

**Comment by srittau** [comment]
No work or obligations on your part. Typeshed contributors will maintain the stubs. It is my hope that eventually more packages will start shipping their own stubs (possibly by starting with the typeshed ones) per [PEP 561](https://www.python.org/dev/peps/pep-0561/), but this purely optional and maturing stubs in typeshed is a good idea anyway.

**Comment by willkg** [comment]
That sounds fine with me! Let me know if you need help with figuring out signatures, though... sounds like you're all set already.

**Comment by willkg** [comment]
Seems like there's no work to be done here, so I'm going to close this out.
