### ISSUE TITLE
Test warnings for python3.7

### ISSUE THREAD

**Issue by kitterma** [mozilla/bleach#425]
With python3.7, I get the following warnings from the test suite:

```
=============================== warnings summary ===============================
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3
  /usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

bleach/sanitizer.py:428
  /tmp/buildd/python-bleach-3.0.2/.pybuild/cpython3_3.7_bleach/build/bleach/sanitizer.py:428: DeprecationWarning: invalid escape sequence \s
    "[`\000-\040\177-\240\s]+",

bleach/sanitizer.py:577
  /tmp/buildd/python-bleach-3.0.2/.pybuild/cpython3_3.7_bleach/build/bleach/sanitizer.py:577: DeprecationWarning: invalid escape sequence \s
    style = re.compile('url\s*\(\s*[^\s)]+?\s*\)\s*').sub(' ', style)

bleach/sanitizer.py:592
  /tmp/buildd/python-bleach-3.0.2/.pybuild/cpython3_3.7_bleach/build/bleach/sanitizer.py:592: DeprecationWarning: invalid escape sequence \s
    if not re.match("^\s*([-\w]+\s*:[^:;]*(;\s*|$))*$", style):

bleach/sanitizer.py:596
  /tmp/buildd/python-bleach-3.0.2/.pybuild/cpython3_3.7_bleach/build/bleach/sanitizer.py:596: DeprecationWarning: invalid escape sequence \w
    for prop, value in re.findall('([-\w]+)\s*:\s*([^:;]*)', style):
```

**Comment by willkg** [comment]
What version of Bleach is that? Is that master tip?

**Comment by willkg** [comment]
I checked and all of these except the html5lib one have been fixed in master.

The warning from html5lib was fixed in https://github.com/html5lib/html5lib-python/commit/4f9235752cea29c5a31721440578b430823a1e69 but that hasn't made it into a release, yet. Once that's released, I can update our vendored copy.

**Comment by brettcannon** [comment]
FYI the html5lib issue now raises an `ImportError` in CPython `master` (i.e. 3.9).

**Comment by fschulze** [comment]
Also see https://github.com/html5lib/html5lib-python/issues/419 as the issue for a new release of html5lib. Since this is vendored anyway, could it be vendored directly without a release?

**Comment by sblondon** [comment]
Release 1.1 from html5lib seems to fix this DeprecationWarning:
https://github.com/html5lib/html5lib-python/blob/master/CHANGES.rst#11

**Comment by hugovk** [comment]
html5lib 1.1 was released to PyPI on Jun 23, 2020:

* https://pypi.org/project/html5lib/#history
