### ISSUE TITLE
Style filter does not work correctly when supplied non-ASCII style attribute

### ISSUE THREAD

**Issue by sekineh** [mozilla/bleach#426]
# Environment

Windows 10 Pro
Python 3.7.1
bleach         3.0.2

I've setup so that `color` style will survive after clean() method like below:
```
>>> bleach.clean('<span style="font-family:consolas;color:red">text</span>', tags = ['span'], attributes = {'span': ['style']}, styles = ['color'])
'<span style="color: red;">text</span>'
```

# Problem

When it contains non-ASCII style description such as Japanese font names, the `color` style is omitted.
```
>>> bleach.clean('<span style="font-family:メイリオ;color:red">text</span>', tags = ['span'], attributes = {'span': ['style']}, styles = ['color'])
'<span style="">text</span>'
```
It should retain the `color` style like below:
```
'<span style="color: red;">text</span>'
```

**Comment by willkg** [comment]
Maybe the `sanitize_css` method needs to be fixed to support non-ascii characters in the attribute value or something like that?

I'd take a PR if someone wants to work on it.

**Comment by sekineh** [comment]
I'll make a PR this week.

**Comment by sekineh** [comment]
Do you have a plan to release a version which includes this fix?
