### ISSUE TITLE
switch CI off travis-ci

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#439]
Bleach currently uses Travis CI for thing, but it seems like Travis CI is going to go away. We should switch to something else.

A lot of Mozilla projects use Circle CI, so I think that's probably the best option for now.

**Comment by g-k** [comment]
see also: #331

**Comment by willkg** [comment]
I was just reading through this post which talks about setting up github actions and testing across linux, macos, and windows:

https://dan.yeaw.me/posts/github-actions-automate-your-python-development-workflow/

Figured maybe that would be helpful.

**Comment by g-k** [comment]
Awesome, that looks great! Thanks willkg

**Comment by hugovk** [comment]
Please see PR https://github.com/mozilla/bleach/pull/514 for testing and linting on GHA.

You'd need to keep Travis at least for Python 3.7 and 3.8 until #503 is fixed, but some jobs could be removed from Travis. 

Some things that Travis has but GHA doesn't, which could be useful: `3.8-dev` and `3.9-dev`. Also up to 4 different CPU architectures (eg. one is big-endian), but that's probably more useful for projects with C code.
