### ISSUE TITLE
Incorrect serialization of html entities without semicolon 

### ISSUE THREAD

**Issue by alvinlindstam** [mozilla/bleach#453]
I am using bleach master and comparing to html5lib 1.0.1.

The serialization of named html entities seems to assume that they contain a semicolon, which they don't have to do:

```python
>>> import bleach
>>> from html5lib import parse, serialize
>>> serialize(parse("&lt test"))
'&lt; test'
>>> bleach.clean("&lt test")
'&amp;lt test'
```

In this example, my understanding is that the html5lib serializer is correct and the bleach serialization is incorrect, since `&lt` is a [valid named html entity](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references).

The html rules are however a bit different if the entity is parsed as part of an html attribute, where named literals without a trailing semicolon is are not treated as a named entity if they are followed by a [colon or an ASCII alphanumeric](https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state):

```python
>>> serialize(parse("<b id='&lt test'/>"), escape_lt_in_attrs=True)
'<b id="&lt; test"></b>'
>>> bleach.clean("<b id='&lt test'/>", attributes={'b': ['id']})
'<b id="&amp;lt test"></b>'
>>> serialize(parse("<b id='&lt=test'/>"), escape_lt_in_attrs=True)
'<b id="&amp;lt=test"></b>'
>>> bleach.clean("<b id='&lt=test'/>", attributes={'b': ['id']})
'<b id="&amp;lt=test"></b>'
```

In the example above, my understanding is again that html5lib is correct while bleach is only correct for the second input. I am not super familiar with the bleach codebase, but it seemed that we are parsing and escaping the html entities ourselves (not using the `consume_entities` in the parser or the `resolve_entities` in the serializer), and that we do so unaware of the context (attribute vs data state) where the rules are different, which I think could lead to this sort of over-escaping.

**Comment by willkg** [comment]
Bleach is not an html5 parser. It's designed to sanitize strings that may or may not be html5 so they can be rendered in an html5 context. Because of that, it's got a very different mission than html5lib and thus Bleach overrides parts of the html5lib parser and tokenizer so that the tokenizing and parsing steps aren't destructively changing the text before the sanitization step.

In this case, Bleach intentionally doesn't consume entities with ambiguous ampersands. That's covered in PR #360. There's some discussion of it in the PR as well as in issue #359.

Hope that helps!

**Comment by alvinlindstam** [comment]
Thanks for the quick response.

I don't really understand that. I was under the impression that running bleach on an input would preserve it's html semantics for the tags and attributes that was allowed. Other html entities are preserved, so I would think that the same would apply for all valid html entities.

The links you provided was about ambiguous ampersands, as defined in https://html.spec.whatwg.org/multipage/syntax.html#syntax-ambiguous-ampersand. `&lt` (and other named entities that exist in [the named entities table](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references)) is not an ambiguous ampersand, it is a valid named entity. So I am unsure about their relevance.

**Comment by alvinlindstam** [comment]
> Given a fragment of HTML, Bleach will parse it according to the HTML5 parsing algorithm and sanitize any disallowed tags or attributes.

From https://bleach.readthedocs.io/en/latest/clean.html#clean-chapter. This seems like we should parse it as html5 and strip unexpected tags/attributes.

Since `&lt test`, parsed according to the html5 specification is the text `< test`, I would expect `bleach.clean("&lt test")` to return `&lt test` (preserving original format) or `&lt; test` (well formed).

**Comment by willkg** [comment]
Sorry! So this is part of a huge problem I spent multiple years working through after reworking Bleach for 2.0 to work with html5lib's filter api. However, I haven't thought about this in a while and so I don't have the entire situation loaded in my head. You're right--that one PR doesn't cover the whole story.

Here are some others that are part of the story:

* https://github.com/mozilla/bleach/issues/143
* https://github.com/mozilla/bleach/issues/294 and https://github.com/mozilla/bleach/pull/321

I don't have this all in my head and I don't want to spend the time right now to go through everything. Skimming issues and pull requests, I really think I did my due diligence to work through all the issues involved and did the right thing and that we shouldn't it. I do understand you find it perplexing. Hopefully the links to the material helps.

**Comment by jvanasco** [comment]
I encountered this again recently outside of bleach during some tests porting an internal tool from Python2 to Python3.

A quick solution that can be implemented by developers is to just `escape(unescape())` the input before sending it to bleach.  

The following code is for PY2/PY3:

```
import six
if six.PY2:
    from backports.html import unescape as _html_unescape_function
    from backports.html import escape as _html_escape_function
else:
    from html import unescape as _html_unescape_function
    from html import escape as _html_escape_function

input = "&lt &lt;"
input_standardized = _html_escape_function(_html_unescape_function(input))
```

Py3's `html.escape` uses the current entity tables, which supports many of the entities that do not have a trailing semicolon.  

Py2 had an undocumented escape that was widely used, and also used internally by HtmlParser - but that does not support the current character table - so the backports version is necessary.

This solution does not utilize a HTML parser, it's all regex under the hood, so there may be some edge cases.  This has passed all our use cases though.

While I personally think bleach should handle stuff like this, I don't think it is necessary when invoking `bleach` is only a component of your user input sanitization routine.

**Comment by DylanYoung** [comment]
I was reading through those issues and I think this is only tangentially related, though maybe I'm misunderstanding something. 

Shouldn't it be just a matter of some small changes starting somewhere around line 492 of html5lib_shim.  In particular removing the ';' check on lines 500 and 511 and maybe addressing that FIXME?  It looks like the FIXME is guarded against in the serializer with a call to `convert_entity`, but not necessarily in the the `Filter.sanitize_characters` (does that mean an Entity token could currently be created with an invalid entity?)

```
        # FIXME(willkg): Do we want to make sure these are valid number
        # entities? This doesn't do that currently.
        while stream and stream[0] not in end_characters:
            c = stream.pop(0)
            if c not in allowed:
                break
            possible_entity += c

        if possible_entity and stream and stream[0] == ';':
            return possible_entity
        return None

    # Handle character entities
    while stream and stream[0] not in end_characters:
        c = stream.pop(0)
        if not ENTITIES_TRIE.has_keys_with_prefix(possible_entity):
            break
        possible_entity += c

    if possible_entity and stream and stream[0] == ';':
        return possible_entity
```

**Comment by DylanYoung** [comment]
Hmmmm...more correct maybe would be to check explicitly perhaps if it's in the entities that are allowed to not end in a semicolon:

```
>>> {e for e in html.entities.html5 if e +';' in html.entities.html5}
{'Ccedil', 'eth', 'Aacute', 'ugrave', 'ucirc', 'Iacute', 'AElig', 'Ugrave', 'ocirc', 'Yacute', 'iquest', 'thorn', 'auml', 'copy', 'LT', 'Icirc', 'sect', 'uacute', 'amp', 'quot', 'gt', 'Ntilde', 'aacute', 'Euml', 'ograve', 'COPY', 'iuml', 'Uacute', 'Auml', 'pound', 'shy', 'lt', 'not', 'ntilde', 'cent', 'reg', 'ETH', 'frac14', 'aring', 'middot', 'times', 'eacute', 'Oslash', 'sup3', 'Oacute', 'micro', 'deg', 'cedil', 'euml', 'otilde', 'icirc', 'curren', 'THORN', 'sup1', 'Eacute', 'AMP', 'ordm', 'Ucirc', 'sup2', 'yen', 'laquo', 'macr', 'ordf', 'yuml', 'ecirc', 'Ograve', 'QUOT', 'para', 'atilde', 'Uuml', 'agrave', 'Ecirc', 'yacute', 'Ouml', 'uml', 'Igrave', 'szlig', 'REG', 'ouml', 'igrave', 'uuml', 'Iuml', 'Agrave', 'Atilde', 'divide', 'Acirc', 'Otilde', 'acute', 'egrave', 'acirc', 'brvbar', 'frac12', 'raquo', 'iexcl', 'Aring', 'Egrave', 'frac34', 'aelig', 'ccedil', 'GT', 'plusmn', 'oslash', 'oacute', 'iacute', 'Ocirc', 'nbsp'}
```

**Comment by DylanYoung** [comment]
After looking at the standard and playing wth chrome, there's a little bit more work, but not much.   I can take a crack if you're interested.  (frankly the patch I proposed would do, it just incorrectly handles both the attribute case (you need to check if the next char is '=' or alphanumeric ascii; if not then resolve the entity) and the text case (if the prefix isn't actually an entity, you need to backtrack and find the entity that matched if there was one, for example with `&noti`, or keep track of which ones are actual matches along the way).  Some edge cases there.

**Comment by willkg** [comment]
I spent some time today re-reading this issue and the linked issues and PRs. I still think Bleach is doing the right thing here where it treats ambiguous character entities (e.g. something without a semicolon) as text and not as a character entity. In serialization, it escapes the "&". That gives us this behavior:

```
>>> bleach.clean("&current")
'&amp;current'
```

There have been several issues about ambiguous character entities which I linked to in the comments in this issue.

While it'd be nice if Bleach could accurately figure out exactly what the user that wrote the text intended (character entity? actual text?), it just can't. I've worked on several forum/feedback systems. I can't think of a case where a user typed something like "&lt test" and expected it to be rendered as "< test". Given that, I think Bleach does the best and least surprising thing it can do here.

@quis I think your double semi-colon bug is not covered by this issue. Particularly this:

https://github.com/alphagov/notifications-utils/pull/814/files#diff-f28b3ed23223b000771c34964f74ea35379b271cc8b4fe4191cd0c637b621fbdR928

Can you write up a new issue for that?

**Comment by willkg** [comment]
@quis Nevermind--I think the bug you found is covered in #450.
