### ISSUE TITLE
Need to make bleach.clean() output XML

### ISSUE THREAD

**Issue by vporton** [mozilla/bleach#456]
`bleach.clean()` should have an option to return a well-formed XML fragment.

**Comment by g-k** [comment]
This isn't a goal of the library (see https://bleach.readthedocs.io/en/latest/goals.html#sanitize-for-use-in-html-attributes-css-json-xhtml-svg-or-other-contexts https://bleach.readthedocs.io/en/latest/goals.html#make-malicious-content-look-pretty-or-sane) but you could try some of the stuff in the unofficial https://github.com/jvanasco/bleach_extras library.
