### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#477]
We could:

- [ ] land the external API stubs in typeshed: https://github.com/python/typeshed/search?q=bleach&unscoped_q=bleach
- [ ] add type annotations to internal APIs to catch errors and improve docs
- [ ] run typechecks with mypy or pyre in CI (edit: prefer `mypy` since adding ocaml to the dev env would probably reduce contributions)

Annotations would have to be in comment form to maintain backwards compatibility with Python 2, but we can skip that if #520 lands first.

**Comment by willkg** [comment]
We deprecated this project, so we're not going to implement more features.
