### ISSUE TITLE
add a SECURITY.md file

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#479]
Bleach has a responsible disclosure policy. GitHub supports a `SECURITY.md` file in the repository which shows that off. More details here:

https://help.github.com/en/articles/adding-a-security-policy-to-your-repository

I don't know what other systems will look for that file, but it's probably a good idea to add it.

**Comment by g-k** [comment]
I think @hwine is working on a bot (like the CoC one) for this. Not sure
how far along it is.

**Comment by hwine** [comment]
No bot planned, as the details can vary by project. Especially ones like this one. :)

What is more likely to happen is that a generic one will be places in the [`.github`](https://github.com/mozilla-services/.github/blob/master/SECURITY.md) repo, where it will be the version displayed to users, unless the repo provides a custom one.

Bottom line: feel free to add an appropriate on directly to this repository.

**Comment by g-k** [comment]
OK good to know. Thanks Hal!
