### ISSUE TITLE
skip_tags for sanitizer?

### ISSUE THREAD

**Issue by philsquared** [mozilla/bleach#489]
I couldn't find any previous issues or PRs raised for this, which makes me suspicious that I'm missing something. I did find a number of Stackoverflow, and other, questions about it - with no real resolution (but plenty of misunderstanding).

The short version is: is there any reason that the santizers (e.g. `clean()`) cannot support the same `skip_tags` attribute as the linkifiers? If not then please consider this a feature request.

The use case is when accepting input (typically coming from markdown, or similar, sources - but this is not specific to that) that contains `<code>` tags (and, a similar situation with `<pre>`). In fact I'm sure this Github issue tracker must have to deal with the same thing!

Entities within `<code>` that would otherwise be treated as html entities (e.g. `<`) should _not_ be escaped in this context. I followed the whole discussion about it through the evolution of `linkify` - from `skip_pre` and a proposed `skip_code` to the generalised `skip_tags`. So I was puzzled why `clean()` does not have the same facility?

**Comment by willkg** [comment]
I can't reproduce this:

```
>>> import bleach
>>> bleach.__version__
>>> bleach.clean("<code><i>select_me</i>()</code>")
'<code><i>select_me</i>()</code>'
```

Do you have a test case that you're having problems with?

**Comment by willkg** [comment]
Given no response, I'm going to close this out.
