### ISSUE TITLE
Add tests for Linker with `build_email_re`

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#497]
PR #486 (landed in #496) adds an email re linkifier that changes email address linking behavior.

Add unit tests from https://blogs.msdn.microsoft.com/testing123/2009/02/06/email-address-test-cases/ to capture that behavior and changes to it and see if it fixes #60 too.

**Comment by willkg** [comment]
I checked issue #60 and it's still a problem. However, I'm going to close this out without doing more work here.
