### ISSUE TITLE
Test suite fails with Python 3.8.1

### ISSUE THREAD

**Issue by Ma27** [mozilla/bleach#503]
This happens since `urllib.parse` parses URLs like `path:80` as `scheme=path,path=80` (https://bugs.python.org/issue27657).

Which causes errors like this:

```
def test_uri_value_allowed_protocols(data, kwargs, expected):
>       assert clean(data, **kwargs) == expected
E       assert '<a>valid</a>' == '<a href="192...00">valid</a>'
E         - <a>valid</a>
E         + <a href="192.168.100.100:8000">valid</a>

tests/test_clean.py:676: AssertionError
```

Currently preparing a patch for this :)

**Comment by hugovk** [comment]
@Ma27 Hi, any progress with the patch? Thanks!

**Comment by Ma27** [comment]
Huh, I thought I provided a status update here as well, sorry!

Unfortunately I'm not sure if I actually want to work around this, the code already depends on some heuristics and I'm afraid that patching around in there will cause some mean regressions.

I still hope that the change gets reverted again: https://github.com/python/cpython/pull/16839#issuecomment-570758153

**Comment by kitterma** [comment]
I don't see much evidence of upstream python3.8 activity to revert.  Even if they do, the same problem will occur once 3.9 is out, so it's got to be solved sooner or later.

**Comment by Ma27** [comment]
>  Even if they do, the same problem will occur once 3.9 is out, so it's got to be solved sooner or later.

Agreed. While taking a look at this a few months ago I realized though that sanitizing has more culprits than I anticipated, so unless the change is reverted, someone else should fix the library accordingly.
