### ISSUE TITLE
Renumber headings

### ISSUE THREAD

**Issue by mitar** [mozilla/bleach#508]
I would like to allow only `h3` or lower headings, while forcing `h1` and `h2` headings to be converted to `h3`. I do not see this being possible currently?

**Comment by g-k** [comment]
It is currently not possible and not one of the goals of bleach, but you could try a custom html5lib filter e.g. https://html5lib.readthedocs.io/en/latest/html5lib.filters.html#module-html5lib.filters.inject_meta_charset
