### ISSUE TITLE
Upload Py2/Py3 wheel packages to PyPI for v3.1.1

### ISSUE THREAD

**Issue by atodorov** [mozilla/bleach#517]
Previous version was shipping wheel packages, please upload them fr the new 3.1.1 version as well.

Thanks.

**Comment by g-k** [comment]
Good catch! 

Uploaded: https://pypi.org/project/bleach/#copy-hash-modal-dfd1673b-e2a4-4d10-96b6-812890b18c46

**Comment by jonathanmeier5** [comment]
Just a heads up this re-upload broke `Pipfile.lock` files in several projects for me.

Releases are hard, thanks for maintaining this project!
