### ISSUE TITLE
TLDS are not up to date

### ISSUE THREAD

**Issue by livid** [mozilla/bleach#519]
https://github.com/mozilla/bleach/blob/e0ad450828832e9548d256f0938823a366337368/bleach/linkifier.py#L14

Currently, all the supported TLDs are defined as a global in linkifier.py, while IANA has a much longer list here:

https://data.iana.org/TLD/tlds-alpha-by-domain.txt

Thus some new and popular TLDs cannot be recognized now, for example, .live .rocks.

**Comment by livid** [comment]
After digging into the docs a bit, I found a workaround:

https://bleach.readthedocs.io/en/latest/linkify.html

```
from bleach.linkifier import Linker, build_url_re

tlds = bleach.linkifier.TLDS
tlds.append(u'live')
tlds.append(u'rocks')
tlds.append(u'sony')
tlds.append(u'google')

improved_url_re = build_url_re(tlds=tlds)
linker = Linker(url_re=improved_url_re)
```

Then `linker.linkify()` would work with those new TLDs.

**Comment by g-k** [comment]
Yep, we're not trying to keep the TLD list up to date. Glad you found the workaround in the docs.

**Comment by last-partizan** [comment]
Why do you not trying to keep list up-to-date? This can be fixed in one place, instead of everybody using workarounds.
