### ISSUE TITLE
Drop support for EOL Python versions <3.6

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#520]
Kinda blocked on html5lib switching to Python 3, but this would:

* let us drop the dependency on `six` (pending html5lib doing the same)
* add Python 3 type annotations (outside comments) 
* use other Python 3 features
* reduce compat and testing burden

TODO: 

- [ ] ~~check Python 2/2.7 usage stats https://pypistats.org/packages/bleach~~
- [ ] ~~see if major library consumers in the ecosystem would be impacted~~

Given that CPython 2.7 support is ending I think it's safe to drop Python 2 support with the next major release.

**Comment by jvanasco** [comment]
What about announcing that `4.0` will drop Python2 support, so people can pin dependencies for auto upgrades now?

**Comment by g-k** [comment]
Absolutely, do you have any suggestions on where to announce that?

**Comment by g-k** [comment]
We should also drop support for unsupported python 3 versions too currently everything <3.6 https://en.wikipedia.org/wiki/History_of_Python#Version_3
