### ISSUE TITLE
version <3.1.4 vulnerarble to Ubuntu Debian?

### ISSUE THREAD

**Issue by Apoorve73** [mozilla/bleach#528]

**Comment by g-k** [comment]
I'm not sure I understand the question, but versions <3.1.4 might be vulnerable on older versions of Ubuntu or Debian. I'd recommend checking the advisories https://github.com/mozilla/bleach/security/advisories?state=published and which version your distro maintainers packaged.

**Comment by kitterma** [comment]
Note: I'm the primary Debian maintainer for bleach:

I'm working on an update for Debian Stable (Buster).  3.1.4 is already uploaded to Unstable and should be in Testing shortly.  I have not evaluated if it is feasible yet to address this in earlier releases (they have a very old bleach).

I'm not involved in Ubuntu development, but I did check and bleach is in their 'Universe' component which means it is not supported by the Ubuntu Security Team.  Unless some community member provides an update it won't be fixed.  Given that no one has updated bleach for the security fixes in 3.1.1 and 3.1.2, I doubt it will happen.
