### ISSUE TITLE
support dashes in style attributes 

### ISSUE THREAD

**Issue by Alex3917** [mozilla/bleach#529]
As part of the changelog for 3.1.4, support for style attributes with dashes (e.g. "font-weight") has been removed. Is there a plan to add support for this back, even if it's just done as a whitelist for commonly used style attributes? Obviously there are valid use cases for these attributes to be in an HTML document.

**Comment by kiilerix** [comment]
My suggestion: https://github.com/mozilla/bleach/pull/530

**Comment by g-k** [comment]
Yes, we're discussing options in https://github.com/mozilla/bleach/issues/248, but want to get away from using a single regex to validate CSS.

**Comment by kiilerix** [comment]
Full css validation would be a nice feature. But would it also solve security issues? (If there are security issues in the existing simple css validation, then they will probably be in valid css that would pass full css validation?)

For me as user of bleach, full css validation would be a feature that I wouldn't appreciate in a minor bugfix release. Conversely, while I much appreciate 3.1.4 fixed a DoS issue, it is annoying that it also introduce unnecessary regressions. It would be very nice to follow up with a minor release that both has the DoS fix and avoids the regression mentioned here.

**Comment by g-k** [comment]
> Full css validation would be a nice feature. But would it also solve security issues? (If there are security issues in the existing simple css validation, then they will probably be in valid css that would pass full css validation?)

Yes, using a CSS parser with simpler or no regexes should make it easier to confirm that we don't have ReDoS vulnerabilities in `bleach`, and that we don't reintroduce them as the regexes drift. We would still have to sanitize the resulting CSS.

> For me as user of bleach, full css validation would be a feature that I wouldn't appreciate in a minor bugfix release.

It would probably be a minor version release.

> It would be very nice to follow up with a minor release that both has the DoS fix and avoids the regression mentioned here.

That would be nice. We did look at options to avoid regressions, but ultimately decided to get a patch out sooner than later.

Thanks for your input!

**Comment by tony** [comment]
Hi there, not to intrude:  To clarify the conversation, will negative *values*, e.g. `style="top: -3.063em; margin-right: 0.05em;` be considered a regression?  [KaTeX](https://katex.org/) generates HTML like this to represent super/subscript.

_If_ that is the case, should the issue title be updated?

**Comment by EmilStenstrom** [comment]
To clarify this issue: The title and original issue talks about dashes in attributes and gives a **property** (font-weight) as an example. This seems now to work, and the issue with with the **values**, as in **-apple-system**, or **-3.5em**.

**Comment by Alex3917** [comment]
@EmilStenstrom This is still getting stripped out for me in 3.2.0: `style="font-weight: normal;"`

**Comment by EmilStenstrom** [comment]
@Alex3917 not for me: https://github.com/mozilla/bleach/issues/547

**Comment by Alex3917** [comment]
@EmilStenstrom OK it seems to fail with certain tags. I changed your test case to demonstrate:

**Code:**
```
import bleach

TESTCASES = [
    """<div style='font-weight: normal;'></div>""",
    """<a style='font-weight: normal;'></a>""",]

for case in TESTCASES:
    print(bleach.clean(case, tags=['div', 'a'], attributes={'div': ['style']}, styles=["font-weight"]))

```

**Output:**
```
<div style="font-weight: normal;"></div>
<a></a>
```

**Comment by Alex3917** [comment]
@EmilStenstrom Ah ok, it seems to work but only in cases where the `<style>` tag doesn't also contain another value that starts with a dash, e.g.:


```
import bleach

TEST_CASES = [
    """<a style='font-weight:normal; -webkit-text-stroke-width: 0px;'>aoeu</a>""",
    """<a style='font-weight:normal;'>aoeu</a>"""
]

for test_case in TEST_CASES:
    print(bleach.clean(test_case, tags=['a'], attributes={'*': ['style']}, styles=["font-weight"]))
```

**Comment by EmilStenstrom** [comment]
@Alex3917 Yep, it's dashes in values which are the problem here.

**Comment by t-ionut** [comment]
Hi! Just tested the below sample with v4.1.0 and dashes in style values still seem to be problematic. Is there any intention of merging #530?

```
In [5]: bleach.clean("""<span style='font-family: "Arial","sans-serif";'></span>""", tags=['span'], attributes={'span': 'style'}, styles=['font-family'])
Out[5]: '<span style=""></span>'
```

**Comment by tony** [comment]
To clarify things, since I couldn't find a PR for it, is https://github.com/mozilla/bleach/commit/d6018f2539d271963c3e7f54f36ef11900363c69 the commit where the happened? (Looks so!)

**Comment by g-k** [comment]
> To clarify things, since I couldn't find a PR for it, is https://github.com/mozilla/bleach/commit/d6018f2539d271963c3e7f54f36ef11900363c69 the commit where the happened? (Looks so!)

Yep!

Closing since @willkg fixed this in 5.x.

**Comment by MahmoudHegazi** [comment]
after many tests the issue was in  double quotes in the font family name for example `font-family: "New Times Roman"; ` will not work if replaced `'&quot;' ` with `"\'"`  it will work for more security I just replaced the known font families that contains quotes sent by summeronte editor with single qoutes

also take care when do this as double quotes may break the security

**Comment by willkg** [comment]
@MahmoudHegazi This issue was fixed in 5.x. If you're using bleach >= 5.0.0 and have an issue, you should open up a new bug.
