### ISSUE TITLE
Split API into safe/recipes and hazmat 

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#539]
> I wonder if the ongoing "Bleach does it right by default but then lets
users do whatever with warnings of dire but vague consequences"
architecture changes we're making should also be accompanied by something
that can help users know when their overrides create bad situations.

1. take a cue from https://cryptography.io/en/latest/#layout and split the
API into a safe and potentially a more stable "recipes" layer (just
bleach.clean, bleach.linkify, and maybe some other top-level functions
taking a limited subset of args) and a more dangerous "hazmat" layer with
all the knobs and buttons to tweak and override things. Security bugs
against the recipes layer would be higher severity.

_Originally posted by @g-k in https://github.com/mozilla/bleach/pull/535#issuecomment-642734522_

**Comment by willkg** [comment]
I think this is interesting, but it's probably a fundamental change to Bleach architecture and there are no plans for that, so I'm going to close it out.
