### ISSUE TITLE
Escape Comments Option

### ISSUE THREAD

**Issue by DylanYoung** [mozilla/bleach#540]
When `strip_comments` is `False`, there doesn't seem to be the ability to escape comments.  Seems like `bleach` should support escaping comments as well. 

Because of the way `strip_comments` was implemented, it's not entirely clear how to go about implementing this.  

Could add another value `strip_comments = None`, but this might cause backwards incompatibility issues (since None is falsy).

Could use a specific value `strip_comments = ESCAPE_COMMENTS`, but this is ugly. 

What I'd suggest is adding a special symbol and simply using the regular `allowed_tags` argument to also allow comments and piggy_backing on `strip` to determine whether it's stripped or escaped. 

Alternatively, a new kwarg: `target_comments` could be introduced, which would respect the `strip` parameter.

**Comment by g-k** [comment]
This sounds out of scope, but what's the use case for escaping comments?

**Comment by willkg** [comment]
It's unclear what the use case is here, but the reporter hasn't replied in over a year, so I'm going to close this out.

**Comment by DylanYoung** [comment]
Probably right that it's out-of-scope.  Can't remember why I filed it, lol, but one case that comes to mind is IE compatibility comments.   All good :)
