### ISSUE TITLE
How can I allow a special angle-bracket tag e.g. <!@zerocool>?

### ISSUE THREAD

**Issue by burritoIand** [mozilla/bleach#546]
I'd like to allow the above mentioned tag in my string e.g. <!@{ID}>. How can I achieve this with bleach?

**Comment by g-k** [comment]
AFAIK this isn't possible. I don't think `<!@zerocool>` is a valid tag and html5lib 1.1 is parsing `<!@zerocool>` as a comment:

```python
» python
Python 3.8.2 (default, Mar 26 2020, 12:39:19) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> bleach.__version__
'3.2.0'
>>> bleach.clean('<!@zerocool>', strip_comments=False)
'<!--@zerocool-->'
>>> 
```

**Comment by burritoIand** [comment]
ok yeah figured out a way around it, have to first parse it out w/regex, then place into a custom tag, and allow that tag w/bleach, then process after.. thanks
