### ISSUE TITLE
add issue template

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#550]
add new issue template to reduce support overhead. Prompt issue reporter for:

- [ ] use case and confirmation that it's in scope for bleach (for feature requests)
- [ ] example bleach call and data and intended output (for feature requests) or expected output (for regressions/bugs)
- [ ] python version
- [ ] bleach version
- [ ] link to CoC (I believe GH links to it already)

cc @hwine @willkg for recommendations for anything else that would be useful

**Comment by hwine** [comment]
lgtm, AND seems like a good time to add a [security policy](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository#adding-a-security-policy-to-your-repository) while you're at it.

We don't have an org wide policy, as there isn't a centralized process. Bleach is the kind of project that "probably should" have one. (While looking for that link, I learned that GitHub is now "supporting" a [.github/SUPPORT.md](https://docs.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project) file. I don't know if that is applicable here.)

**Comment by g-k** [comment]
Thanks Hal! We added a security policy in #479 

Do you want me to ask around about setting an org-wide one?

CVEs for client side end user apps go through BMO and the security@ list (i.e. gecko-dev and mobile apps) and we can disclose CVEs for service, server, and server libs on GH.

I'm less sure about shared components and libs like geckoview.
