### ISSUE TITLE
add fuzz / property-based tests

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#552]
e.g. with https://hypothesis.works/

**Comment by Google-Autofuzz** [comment]
I'm currently trying to get bleach integrated with OSS-Fuzz: https://github.com/google/oss-fuzz/pull/4959

@g-k would you be interested in being the primary contact?

**Comment by g-k** [comment]
@Google-Autofuzz yes, I can be the primary contact. Thanks!

**Comment by Google-Autofuzz** [comment]
Can you please give me an email address with an associated google account?

**Comment by g-k** [comment]
How about gguthe@mozilla.com ? Is a gsuite email OK or does it have to be a
gmail account?
