### ISSUE TITLE
bug: DeprecationWarning: html5lib's sanitizer is deprecated

### ISSUE THREAD

**Issue by pllim** [mozilla/bleach#557]
**Describe the bug**

Hello. This deprecation has come up in our project's CI as such ([full log](https://travis-ci.org/github/astropy/astropy/jobs/727949664)):
```
.../astropy/utils/xml/writer.py:195: in <lambda>
    self.xml_escape_cdata = lambda x: bleach.clean(x, **clean_kwargs)
.../bleach/__init__.py:84: in clean
    return cleaner.clean(text)
.../bleach/sanitizer.py:175: in clean
    filtered = BleachSanitizerFilter(
.../bleach/sanitizer.py:273: in __init__
    return super(BleachSanitizerFilter, self).__init__(source, **kwargs)
...
E       DeprecationWarning: html5lib's sanitizer is deprecated;
see https://github.com/html5lib/html5lib-python/issues/443 and
please let us know if Bleach is unsuitable for your needs
```
As the traceback says, we are already using Bleach (3.2.0).

I asked over at https://github.com/html5lib/html5lib-python/issues/443#issuecomment-694211077 and it was suggested that I open a bug report here. Thank you!

**python and bleach versions (please complete the following information):**

 - Python Version: 3.8.1
 - Bleach Version: 3.2.0

**To Reproduce**

Steps to reproduce the behavior: Is the traceback sufficient?

**Expected behavior**

No deprecation warning, because I am not sure if there is anything I can do about it, except ignoring the warning.

**Additional context**

Our CI turns deprecation warnings into failures.

**Comment by g-k** [comment]
Hi, thanks for the report!

The traceback is sufficient. I'll add some tests that warnings aren't propagated.
