### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by millerthegorilla** [mozilla/bleach#582]
**Describe the bug**
bleach doesn't strip onerror attribute
A clear and concise description of what the bug is. [e.g. "`bleach.clean` does not escape script tag contents"]
bleach.clean does not strip onerror attribute
** python and bleach versions (please complete the following information):**
Python version 3.9.1
Bleach 3.2.2
 - Python Version: [e.g. 3.8.2]
 - Bleach Version: [e.g. 3.2.0]

**To Reproduce**

I am using django with a rich text editor (summernote, and tinymce so far), and catching the text on form validation with the following text:
```
<img src=x onerror=alert('XSS');>
```
I then use bleach.clean with a set of allowed tags, attributes and styles and strip=True

**Expected behavior**
the text to be cleaned 
 ```
    <img src=x>
```

**Additional context**
instead I get a copy of the original string, and when displayed as a post I get an xss injection alert.
as reported in https://github.com/summernote/django-summernote/issues/415

**Comment by g-k** [comment]
Hi @millerthegorilla, thanks for the report.

Can you be more specific about what arguments you're passing to `clean`? Are you using the allowed tags and attrs from https://github.com/summernote/django-summernote/blob/699db68dc33b782775369813034f8b2a0e17e377/django_summernote/settings.py?

I can't reproduce the issue using those settings with the call to `clean` at https://github.com/summernote/django-summernote/blob/c481579d49b442b3f2516cad84b68633c553ae48/django_summernote/fields.py#L18:

```python
$ cat settings.py
ALLOWED_TAGS = [
    'a', 'div', 'p', 'span', 'img', 'em', 'i', 'li', 'ol', 'ul', 'strong', 'br',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'table', 'tbody', 'thead', 'tr', 'td',
    'abbr', 'acronym', 'b', 'blockquote', 'code', 'strike', 'u', 'sup', 'sub',
]

STYLES = [
    'background-color', 'font-size', 'line-height', 'color', 'font-family'
]

ATTRIBUTES = {
    '*': ['style', 'align', 'title', ],
    'a': ['href', ],
}
$ python
Python 3.8.6 (default, Oct  6 2020, 15:47:43) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import settings
>>> from bleach import clean
>>> clean("<img src=x onerror=alert('XSS');>", tags=settings.ALLOWED_TAGS, attributes=settings.ATTRIBUTES, styles=settings.STYLES)
'<img>'
```

**Comment by millerthegorilla** [comment]
Thanks for your help.   I was obtaining the text from the form by saving it, and django's safe tag escaped some entities leaving me with  "<p>&lt;img src=x onerror=alert('XSS');&gt;</p>"
bleach.clean failed to clean it, and I was then running html.unescape in order to use django's mark_safe function to create a 'safestring' object for display.
I now unescape the text after it has been saved by the form before running bleach.clean and it works as expected.
Cheers!
