### ISSUE TITLE
add support for args and kwargs to the test website server

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#583]
Currently, it [runs clean without args or kwargs](https://github.com/mozilla/bleach/blob/master/tests_website/server.py#L33)

Per chat with willkg, it'd be handy to have it run the tests for other things like https://github.com/mozilla/bleach/security/advisories/GHSA-vv2x-vrpj-qqpq so we don't have to copy output into the browser.

**Comment by willkg** [comment]
We deprecated this project, so we're not going to implement more features.
