### ISSUE TITLE
publish static site

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#584]
Publish the static test website to GH pages with a WASM implementation of python e.g. https://pyodide.readthedocs.io/en/latest/index.html

**Comment by g-k** [comment]
Played with this a bit in https://github.com/mozilla/bleach/compare/master...fix-584-static-site but saw:

![image](https://user-images.githubusercontent.com/226605/106778917-77c96b00-6614-11eb-8c40-a07c871fe0e3.png)

on https://pyodide-cdn2.iodide.io/v0.16.1/full/console.html

so I tried a local site. Pyodide installs and runs the right version of bleach, but https://github.com/jcubic/jquery.terminal is unescaping the (tested via breaking on `term.handlePythonResult` in `console.html` then `term.echo("&lt;")` results in `<span data-text="<">&lt;</span>` HTML and `<span data-text="<"><</span>` in the DOM).

I think we'd host this at: `https://mozilla.github.io/bleach/<bleach version>` or `bleach/playground/<bleach version>` with a symlinks to tip or stable/release and build it in a GHA.

Note that an old gh-pages branch already exists.

**Comment by g-k** [comment]
Should be easier with CPython WASM builds in 3.11 https://bugs.python.org/issue40280

**Comment by willkg** [comment]
This is a neat idea, but in the interests of paring the project down, I'm going to wontfix this.
