### ISSUE TITLE
Feature Request: clear "unvendoring" policy.

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#587]
Bleach vendors html5lib. There is a clear vendoring policy (https://github.com/mozilla/bleach/blob/master/bleach/_vendor/README.rst)

I respectfully request an unvendoring policy be added to the repo/ReadMe. Basically, it would be great if there were some guarantee that unvendoring html5lib will not happen in patch release, but either a major or minor version change.

The reason for this: When developing filters to use with bleach, it is safer to pull in the vendored parent classes from `bleach.html5lib_shim`- otherwise we run into potential concerns with version/api compatibilities.  If there is some clarity around this matter, we can pin versions to avoid things breaking.

**Comment by g-k** [comment]
I don't have any plans to unvendor html5lib, but can commit to not unvendoring it in a patch release.

To document (un)vendoring policy and our general versioning policy I think we'll:

- [ ] add unvendoring policy to the vendor readme
- [ ] document our versioning policy in the top-level readme including unvendor/vendoring policy and what interfaces we consider public for semver purposes
- [ ] update release process dev doc

**Comment by jvanasco** [comment]
> I don't have any plans to unvendor html5lib, but can commit to not unvendoring it in a patch release.

Thanks, @g-k!  I'm familiar with all the maintainer's arguments for vendoring, so I really don't think you are likely to unvendor it... but having a policy like that is a very comforting notion to avoid breaking changes!
