### ISSUE TITLE
bleach.clean wrong output with p and pre tag

### ISSUE THREAD

**Issue by randy1yu** [mozilla/bleach#588]
**Describe the bug**
   bleach.clean  wrong output with p and pre tags

** python and bleach versions (please complete the following information):**

 - Python Version: 3.6.8
 - Bleach Version: 3.3.0

**To Reproduce**

`bleach.clean("<p><pre>text</pre></p>", ["p", "pre"])`

**Expected behavior**
`<p><pre>text</pre></p>`

**Actual behavior**
`<p></p><pre>text</pre><p></p>`

**Comment by g-k** [comment]
Huh, that's weird. I can confirm the regression on Python 3.8.6 / bleach 3.3.0.

Thanks for filing the issue.

**Comment by willkg** [comment]
I'm pretty sure it's not valid for `<pre>` to be a child of `<p>` which is why it's getting fixed this way. I don't think this is a regression.

https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element

**Comment by g-k** [comment]
I had the regression label in the new issue template, so I think too many issues are tagged as regressions now.

I'll have to go back and check how bleach <3.3.0 handled this.

The [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) for `pre` says it allows any flow content tag to be a parent including `p` https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content I'm not sure if the spec or html5lib changed.

**Comment by willkg** [comment]
I skimmed the MDN pages. The page for `pre` says:

> Permitted parents: Any element that _accepts_ flow content.

`p` is flow content. However, the page for `p` says:

> Permitted content: Phrasing content.

and `pre` isn't phrasing content. So I'm pretty sure it's not valid for `pre` to be a child of `p`.

I understand the op finds this irritating and maybe it breaks something in their system, but I don't think this is a bug in Bleach and I don't think we should fix it.

I'm going to close this out. If someone finds HTML spec bits that prove that wrong, I'm game for reopening and thinking about this.
