### ISSUE TITLE
bug: bleach.clean incorrectly strips "style" attribute if any rule contains minus sign

### ISSUE THREAD

**Issue by blidec** [mozilla/bleach#591]
**Describe the bug**

`bleach.clean` incorrectly strips "style" attribute if any rule contains minus sign, which is legit (e.g. top: -187px)

** python and bleach versions (please complete the following information):**

 - Python Version: 3.7
 - Bleach Version: 3.3.0

**To Reproduce**

```pytnon
>>> ALLOWED_TAGS = ['div']
>>> ALLOWED_ATTRIBUTES = {'div': ['style']}
>>> ALLOWED_STYLES = ['cursor', 'position', 'width', 'height', 'top', 'left']
>>> text = """<DIV style="CURSOR: pointer; position: absolute; width: 360px; height: 20px; top: -187px; left: -310px" onclick=""window.open('http://example.com/nosuchpage.html')""> </DIV>"""
>>> bleach.clean(text, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES, styles=ALLOWED_STYLES)
'<div style=""> </div>'
```

However if you remove the minus sign in "top" and "left", then it works fine
```pythnon
>>> text = """<DIV style="CURSOR: pointer; position: absolute; width: 360px; height: 20px; top: 187px; left: 310px" onclick=""window.open('http://example.com/nosuchpage.html')""> </DIV>"""
'<div style="CURSOR: pointer; position: absolute; width: 360px; height: 20px; top: 187px; left: 310px;"> </div>'
```

**Expected behavior**
```python
>>> text = """<DIV style="CURSOR: pointer; position: absolute; width: 360px; height: 20px; top: -187px; left: -310px" onclick=""window.open('http://example.com/nosuchpage.html')""> </DIV>"""
>>> bleach.clean(text, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES, styles=ALLOWED_STYLES)
'<div style="CURSOR: pointer; position: absolute; width: 360px; height: 20px; top: -187px; left: -310px;"> </div>'
```
**Additional context**

gauntlet = re.compile(
            r"""^(  # consider a style attribute value as composed of:
[/:,#%!.\s\w]    # a non-newline character
|\w-\w           # 3 characters in the form \w-\w
|'[\s\w]+'\s*    # a single quoted string of [\s\w]+ with trailing space
|"[\s\w]+"       # a double quoted string of [\s\w]+
|\([\d,%\.\s]+\) # a parenthesized string of one or more digits, commas, periods, ...
)*$""",  # ... percent signs, or whitespace e.g. from 'color: hsl(30,100%,50%)'
            flags=re.U | re.VERBOSE,
        )

**Comment by g-k** [comment]
Yes this is #529
