### ISSUE TITLE
bug: bleach.clean doesn't strip uri if uri is encoded

### ISSUE THREAD

**Issue by blidec** [mozilla/bleach#592]
**Describe the bug**

bleach.clean() failed to strip malicious uri if the uri is encoded. If the uri is plaintext, then everything works fine. E.g.,
```bleach.clean("<img src='javascript:alert('XSS')'>", tags=['img'], attributes={'img':['src']})``` correctly stripped the "src" attribute and output ```<img>```. However when the uri is encoded, the "src" field will be simply escaped instead of being stripped.

**python and bleach versions (please complete the following information):**

 - Python Version: 3.7
 - Bleach Version: 3.3.0

**To Reproduce**

```
bleach.clean('<img src=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>', tags=['img'], attributes={'img':['src']})
```

**Expected behavior**

```<img>```

**Actual behavior**
```
<img src="&amp;#0000106&amp;#0000097&amp;#0000118&amp;#0000097&amp;#0000115&amp;#0000099&amp;#0000114&amp;#0000105&amp;#0000112&amp;#0000116&amp;#0000058&amp;#0000097&amp;#0000108&amp;#0000101&amp;#0000114&amp;#0000116&amp;#0000040&amp;#0000039&amp;#0000088&amp;#0000083&amp;#0000083&amp;#0000039&amp;#0000041">
```

**Additional context**

I believe sanitize_uri_value() or html5lib.convert_entities() should unescape encoding, i.e., if the token starts with "&#"

**Comment by g-k** [comment]
Interesting, I can confirm that behavior on python 3.8.9 and bleach 3.3.0.

As far as I can tell the escaped URI is gross but safe.

Unescaping the in `convert_entities` makes sense, but I'd need to think about it some more.

**Comment by willkg** [comment]
Seems like the output is safe, so seems like Bleach clean is doing what it needs to do here. I'm not sure I agree that the expected output is inherently better.

I don't think there's anything we should do here.
