### ISSUE TITLE
bug: svg href removed if it doesn't start with #

### ISSUE THREAD

**Issue by mnoop** [mozilla/bleach#596]
**Describe the bug**

Part of the svg tag sanitization seems to remove any svg href that doesn't start with #.

https://github.com/mozilla/bleach/blob/3e5d6aa375677821aaf249127e44ac51a815cf2b/bleach/sanitizer.py#L550

I am trying to use a local svg spritesheet with a fragment identifier, but it is not allowed even though it is not external. Is this intentional?

Python 3.6.9
Bleach 3.3.0

**To Reproduce**

```
import bleach

cleaned_html = bleach.clean('<svg><use href="/images/spritesheet.svg#logo"></use></svg>', tags=["svg", "use"], attributes=["href"])

print(cleaned_html)
```

**Expected behavior**

```<svg><use href="/images/spritesheet.svg#logo"></use></svg>```

**Actual behavior**

```<svg><use></use></svg>```

**Comment by yisibl** [comment]
The `<use>` element has an XSS vulnerability.
https://insert-script.blogspot.com/2014/02/svg-fun-time-firefox-svg-vector.html
