### ISSUE TITLE
automate build and release process from CI

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#599]
To avoid #595 again

This should simplify maintenance and improve reproducibility and confidence in the release artifacts (there's probably an OpenSSF standard somewhere for this to track down https://github.com/ossf/scorecard/blob/main/checks/packaging.go#L114).

We can probably crib https://github.com/mozilla/frost/blob/main/.github/workflows/publish.yml

**Comment by jvanasco** [comment]
It might be a good idea to rename `master` to `main` before doing this.

**Comment by willkg** [comment]
We deprecated the project, so we're not going to do this.
