### ISSUE TITLE
Some email addresses are messed up with parse_email=False

### ISSUE THREAD

**Issue by ThiefMaster** [mozilla/bleach#60]
```
>>> linkify('doesntmatter@foo-bar.de')
u'doesntmatter@foo<a href="http://-bar.de" rel="nofollow">-bar.de</a>'
```

**Comment by willkg** [comment]
I'm going to drop this from the milestone. I think it needs more thinking and I'm not going to get to it for v2.0.

**Comment by willkg** [comment]
This is a problem, but this isn't something we're going to fix. Sorry!
