### ISSUE TITLE
handle URLs with an IP and port (but no scheme)

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#611]
Handle URLs with an IP and port (but no scheme) like 192.168.100.100:8000/foo#bar

refs: https://github.com/mozilla/bleach/pull/565#r683588433 and associated discussion in that PR.

One option is updating to Python 3.9 urlparse

**Comment by willkg** [comment]
Bleach is deprecated, so we're not going to fix this issue. Sorry!
