### ISSUE TITLE
feature: Should lxml and genshi be listed explicitly in some configuration files?

### ISSUE THREAD

**Issue by yuluc123** [mozilla/bleach#617]
Hi,
I noticed lxml  and Genshi are used as dependencies in the project for example , _bleach/_vendor/html5lib/treebuilders/etree_lxml.py_. I am wondering if it is necessary to list these dependencies in configuration files.

**Expected Bahavior**
Add lxml and Genshi to configuration files such as requirements-extras.txt

**Comment by g-k** [comment]
We originally vendored html5lib to make it easier to develop and test bleach against a limited set of dependencies.

We won't add optional dependencies to our config files since it makes that harder.
