### ISSUE TITLE
remove six from dependencies

### ISSUE THREAD

**Issue by sevdog** [mozilla/bleach#618]
Since support for Python 2 was removed in [version 2.0](https://github.com/mozilla/bleach/blob/a362171055af36996dc1cedb64c6b3f68359db27/CHANGES#L548) the use of SIX library to handle compatibility between Python 3 and Python 2 has no more meaning (aka: it is a useless dependecy).

See [remaining code using SIX](https://github.com/mozilla/bleach/search?q=six).

**Comment by g-k** [comment]
Happy to accept a PR for this and I'll leave this open to track the issue.

Keep in mind we don't want to edit the vendored html5lib since we'd effectively fork it. Last I checked this would require an upstream release of html5lib.

**Comment by sevdog** [comment]
Now that you mention it, this could be a problem since six is only used in vendored html5lib 🥲 

Before rebasing that folder [this PR](https://github.com/html5lib/html5lib-python/pull/536/files) should be merged by them.

**Comment by willkg** [comment]
I put this in the 5.0.0 milestone because I thought we could do it, but we can't, yet. We're blocked on upstream dropping the need for six.

**Comment by willkg** [comment]
It seems like upstream is no longer maintained. The PR in question was closed. Issue #680 covers forking html5lib or finding an alternative.

**Comment by willkg** [comment]
I think we're waiting on some implementation of this issue and a release:

https://github.com/html5lib/html5lib-python/issues/569

**Comment by willkg** [comment]
I decided not to wait for it to get fixed in html5lib. We can fix it now and adjust when it's fixed in html5lib and there's a release.
