### ISSUE TITLE
Q: vendoring `html5lib` and `parse`

### ISSUE THREAD

**Issue by kloczek** [mozilla/bleach#628]
There are any issues with those two modules that that thay've been bundled into bleach/_vendor?
Just asking because I'm interested those issues if there sometning critical :)
(in bleach/_vendor/README.rst there is no to much details about that)

**Comment by willkg** [comment]
I don't understand what you're asking. Are you asking _why_ we vendored those two modules? Or are you asking whether there are any issues with vendoring those modules that you need to know about? Or something else?

**Comment by willkg** [comment]
Given that there's no reply, I'm closing this out.
