### ISSUE TITLE
feature: support for native sanitizer API builtins and configuration

### ISSUE THREAD

**Issue by g-k** [mozilla/bleach#638]
Consider adopting or providing a compatibility layer to support the native sanitizer API:

- [ ] allow lists for elements https://wicg.github.io/sanitizer-api/#baseline-elements and attributes https://wicg.github.io/sanitizer-api/#baseline-attributes
- [ ] possibly support its configuration format https://wicg.github.io/sanitizer-api/#default-configuration-object

**Comment by willkg** [comment]
We deprecated the project, so we're not going to add any new features.
