### ISSUE TITLE
add tests for XSS examples in OWASP testing guide

### ISSUE THREAD

**Issue by graingert** [mozilla/bleach#66]
Adding all the tests from http://ha.ckers.org/xss.html would be a good idea

**Comment by willkg** [comment]
The site in question isn't available anymore. Looks like some/all of the content was moved to the OWASP testing guide, so I grabbed the stuff in the appendix there.

Having said that, I'm not sure what "enough" entails, so I'm going to change the scope of this to "add tests for the XSS examples listed in the OWASP guide".

**Comment by graingert** [comment]
@willkg sucky, I remember back in 2012, http://ha.ckers.org/xss.html was pretty great.

**Comment by graingert** [comment]
@willkg here's the last good snapshot: https://web.archive.org/web/20120717070023/http://ha.ckers.org/xss.html

**Comment by graingert** [comment]
@willkg and I've got a snapshot on github https://github.com/graingert/xss

**Comment by willkg** [comment]
@graingert Can you go through and add those? If you use the system I used for regression tests, it's not too hard.

**Comment by graingert** [comment]
Sorry I'm way more busy than I was 4 years ago!

**Comment by willkg** [comment]
I added some stuff a while back. We can add new tests as needed. I don't think we need to keep this open forever.
