### ISSUE TITLE
bug: bleach.clean is not handling & symbol very well

### ISSUE THREAD

**Issue by aurangzaib048** [mozilla/bleach#681]
**Describe the bug**

`bleach.clean` is change the & symbol to &amp; which is not good. There good be some flag/parameters to ignore char/sym/words.

** python and bleach versions (please complete the following information):**

 - Python Version: [e.g. 3.9.9]
 - Bleach Version: [e.g. 5.0.1]

**To Reproduce**

[e.g. ```python
>>> bleach.clean("Food & Wine")
"Food &amp; Wine"
```]

**Expected behavior**

[e.g. ```python
>>> bleach.clean("Food & Wine")
"Food & Wine"
```]

**Additional context**

Add any other context about the problem here.

**Comment by willkg** [comment]
You don't explain why this behavior is bad or how it affects you, so it's hard to speak to your specific use case. This seems just like issue #192. Bleach sanitizes text for *html output* and converts bare `&` to the character entity.
