### ISSUE TITLE
Possible to only allow target="_blank" but no other values?

### ISSUE THREAD

**Issue by ThiefMaster** [mozilla/bleach#684]
Is there a way to allow `<a target="_blank" ....>` but no other targets? My usecase is that people sometimes don't know what to use, and if you put `target="blank"` or similar, then it'll set the window name and two links with the same wrong target would open in the same new tab/window instead of separate ones.

**Comment by willkg** [comment]
Can you provide a test case so I know specifically what you're asking about?

**Comment by ThiefMaster** [comment]
```html
<a href="https://google.com" target="_blank">test</a>
<a href="https://google.com" target="foo">test 2</a>
<a href="https://google.com">test 3</a>
```

->

```html
<a href="https://google.com" target="_blank">test</a>
<a href="https://google.com">test 2</a>
<a href="https://google.com">test 3</a>
```

**Comment by willkg** [comment]
There's a `target_blank` callback that you can use which will enforce a `target="_blank"`. Pretty sure that's not what you want, but you can write your own callback and base it on the `target_blank` code.

https://github.com/mozilla/bleach/blob/6f0aaaaa98ff355a1207e7c1c77d3eb0c063a9b1/bleach/callbacks.py#L22-L32

Hope that helps!
