### ISSUE TITLE
bug: linkify with entities inside anchor strings are incorrectly escaped

### ISSUE THREAD

**Issue by mcleanmds** [mozilla/bleach#704]
**Describe the bug**

linkify on a string with entities inside anchor element text results in the `&` character of the entity being incorrect escaped to `&amp;`
e.g. `&nbsp;` -> `&amp;nbsp;`

** python and bleach versions (please complete the following information):**

 - Python Version: 3.9.5
 - Bleach Version: 6.0.0

**To Reproduce**

A simple test to reproduce the behavior:
```python
>>> from bleach import linkify
text = r'<p><a href="/">Some&nbsp;entity&rsquo;s</a>More&nbsp;entity&rsquo;s</p>'
expected = r'<p><a href="/" rel="nofollow">Some&nbsp;entity&rsquo;s</a>More&nbsp;entity&rsquo;s</p>'
assert linkify(text) == expected 
```

**Expected behavior**
```python
linkify(r'<a href="/">Some&nbsp;entity&rsquo;s</a>')
'<a href="/" rel="nofollow">Some&nbsp;entity&rsquo;s</a>'
```

**Actual behavior**
```python
linkify(r'<a href="/">Some&nbsp;entity&rsquo;s</a>')
'<a href="/" rel="nofollow">Some&amp;nbsp;entity&amp;rsquo;s</a>'
```

**Additional context**

This bug was introduced in 6.0.0 with the fix for #501 and #692: https://github.com/mozilla/bleach/pull/692

**Comment by willkg** [comment]
Thank you for the issue!
