### ISSUE TITLE
feature: please provide update for latest `tinycss2==1.3`

### ISSUE THREAD

**Issue by OttoAndrey** [mozilla/bleach#732]
Hi! Is it possible update `tinycss2` to latest version?
https://github.com/Kozea/tinycss2/releases/tag/v1.3.0

Here 
https://github.com/mozilla/bleach/blob/fcbe8f7fb144f3e65cbf00a464433558c80badec/setup.py#L33-L37

**Comment by willkg** [comment]
https://github.com/Kozea/tinycss2/compare/v1.2.1...v1.4.0
