### ISSUE TITLE
Allow style URLs from white-listed domains

### ISSUE THREAD

**Issue by ricobl** [mozilla/bleach#91]
It would be nice to allow urls from white-listed domains instead of stripping every url directive from style attributes.

**Comment by willkg** [comment]
I understand the use case here, but I don't think I want to extend Bleach to handle it.

I just did a Bleach rewrite. You could write some code to subclass ``BleachSanitizerFilter`` and override the ``sanitize_css`` method and do your own thing. I think that's your best course of action.

Sorry if that's not helpful enough.

**Comment by ricobl** [comment]
Hey @willkg, I'm not in the project that uses `bleach` anymore, but thanks for revisiting this issue, sounds like a good approach.
